import { MODULE, STATE_REDUCER_KEY, createAction } from "../common";

export const ACTION_TYPES = {

    SAMPLE_ACTION: `${MODULE}/${STATE_REDUCER_KEY.MARRIAGE}/SAMPLE_ACTION`,
    SAMPLE_ACTION_REQUEST: `${MODULE}/${STATE_REDUCER_KEY.MARRIAGE}/SAMPLE_ACTION_REQUEST`,
    SAMPLE_ACTION_SUCCESS: `${MODULE}/${STATE_REDUCER_KEY.MARRIAGE}/SAMPLE_ACTION_SUCCESS`,
    SAMPLE_ACTION_FAILURE: `${MODULE}/${STATE_REDUCER_KEY.MARRIAGE}/SAMPLE_ACTION_FAILURE`

}

export const callSampleAction = (data) => createAction(ACTION_TYPES.SAMPLE_ACTION, data);