const Urls = {
  MDMS: `/egov-mdms-service/v1/_search`,
  WorkFlow: `/egov-workflow-v2/egov-wf/businessservice/_search`,
  WorkFlowProcessSearch: `/egov-workflow-v2/egov-wf/process/_search`,
  localization: `/localization/messages/v1/_search`,
  location: {
    localities: `/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=ADMIN&boundaryType=Locality`,
    revenue_localities: `/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=REVENUE&boundaryType=Locality`,
  },

  pgr_search: `/pgr-services/v2/request/_search`,
  pgr_update: `/pgr-services/v2/request/_update`,
  filter_data: `https://run.mocky.io/v3/597a50a0-90e5-4a45-b82e-8a2186b760bd`,
  FileStore: "/filestore/v1/files",

  FileFetch: "/filestore/v1/files/url",
  PGR_Create: `/pgr-services/v2/request/_create`,
  pgr_count: `/pgr-services/v2/request/_count`,

  OTP_Send: "/user-otp/v1/_send",
  Authenticate: "/user/oauth/token",
  RegisterUser: "/user/citizen/_create",
  ChangePassword: "/user/password/nologin/_update",
  ChangePassword1: "/user/password/_update",
  UserProfileUpdate: "/user/profile/_update",
  EmployeeSearch: "/egov-hrms/employees/_search",

  InboxSearch: "/inbox/v1/_search",

  UserSearch: "/user/_search",
  UserLogout: "/user/_logout",

  Shortener: "/egov-url-shortening/shortener",

  fsm: {
    search: "/fsm/v1/_search",
    create: "/fsm/v1/_create",
    update: "/fsm/v1/_update",
    vendorSearch: "/vendor/v1/_search",
    vehicleSearch: "/vehicle/v1/_search",
    audit: "/fsm/v1/_audit",
    vehicleTripSearch: "/vehicle/trip/v1/_search",
    billingSlabSearch: "/fsm-calculator/v1/billingSlab/_search",
    vehilceUpdate: "/vehicle/trip/v1/_update",
    vehicleTripCreate: "/vehicle/trip/v1/_create",
  },

  payment: {
    fetch_bill: "/billing-service/bill/v2/_fetchbill",
    demandSearch: "/billing-service/demand/_search",
    create_reciept: "/collection-services/payments/_create",
    print_reciept: "/collection-services/payments",
    generate_pdf: "/pdf-service/v1/_create",
    create_citizen_reciept: "/pg-service/transaction/v1/_create",
    update_citizen_reciept: "/pg-service/transaction/v1/_update",
    search_bill: "/billing-service/bill/v2/_search",
    reciept_search: "/collection-services/payments/:buisnessService/_search",
    obps_Reciept_Search: "/collection-services/payments/_search",
  },

  pt: {
    fectch_property: "/property-services/property/_search",
    fetch_payment_details: "/billing-service/bill/v2/_fetchbill",
    create: "/property-services/property/_create",
    search: "/property-services/property/_search",
    update: "/property-services/property/_update",
    pt_calculation_estimate: "/pt-calculator-v2/propertytax/v2/_estimate",
    assessment_create: "/property-services/assessment/_create",
    assessment_search: "/property-services/assessment/_search",
    payment_search: "/collection-services/payments/PT/_search",
    pt_calculate_mutation: "/pt-calculator-v2/propertytax/mutation/_calculate",
  },

  dss: {
    dashboardConfig: "/dashboard-analytics/dashboard/getDashboardConfig",
    getCharts: "/dashboard-analytics/dashboard/getChartV2",
  },

  mcollect: {
    search: "/echallan-services/eChallan/v1/_search",
    create: "/echallan-services/eChallan/v1/_create?",
    fetch_bill: "/billing-service/bill/v2/_fetchbill?",
    search_bill: "/egov-searcher/bill-genie/mcollectbills/_get",
    search_bill_pt: "/egov-searcher/bill-genie/billswithaddranduser/_get",
    update: "/echallan-services/eChallan/v1/_update",
    download_pdf: "/egov-pdf/download/UC/mcollect-challan",
    receipt_download: "/egov-pdf/download/PAYMENT/consolidatedreceipt",
    bill_download: "/egov-pdf/download/bills/consolidatedbill",
    count: "/echallan-services/eChallan/v1/_count",
  },
  hrms: {
    search: "/egov-hrms/employees/_search",
    count: "/egov-hrms/employees/_count",
    create: "/egov-hrms/employees/_create",
    update: "/egov-hrms/employees/_update",
  },
  tl: {
    create: "/tl-services/v1/_create",
    search: "/tl-services/v1/_search",
    fetch_payment_details: "/billing-service/bill/v2/_fetchbill",
    download_pdf: "/egov-pdf/download/TL/",
    update: "/tl-services/v1/_update",
    billingslab: "/tl-calculator/billingslab/_search",
    createpde: "/tl-services/pde/_create",
    searchpde: "/tl-services/pde/_search",
    updatepde: "/tl-services/pde/_update",
    updatepdewf: "/tl-services/pde/_updatewf",
    createcorrection: "/tl-services/correction/_create",
    updatecorrection: "/tl-services/correction/_update",
  },
  cr: {
    create: "/birth-services/cr/createbirth",
    search: "/birth-services/cr/searchbirth",
    adoption_search: "/birth-services/cr/searchadoption",
    adoption_update: "/birth-services/cr/updateadoption",
    update: "/birth-services/cr/updatebirth",
    download_pdf: "/egov-pdf/download/CR/",
    registry_download: "/birth-services/cr/registry/_download",
    registry_search_birth: "/birth-services/cr/registry/_search",
    create_adoption: "/birth-services/cr/createadoption",
    correct_update: "/birth-services/cr/createbirthcorrection",
    registry_search_Adoption: "/birth-services/cr/registry/_searchAdoption",
  },
  crcorrection: {
    marriage_correction_search: "/marriage-services/v1/marriagedetails/_searchmarriage",
    marriage_correction_details:"/marriage-services/v1/marriagedetails/_searchmarriagecorrection",
    birth_correction_search: "/birth-services/cr/searchbirthcorrection",
    birth_correction_update: "/birth-services/cr/updatebirthcorrection",
    death_correction_search: "/birth-services/cr/searchbirthcorrection"
  },
  crcommonpayment: {
    update: "/birth-services/cr/common/updatepaywf",
    update_status: "/egov-workflow-v2/egov-wf/process/_transition",
  },
  crstillbirth: {
    create: "/birth-services/cr/createstillbirth",
    search: "/birth-services/cr/searchstillbirth",
    update: "/birth-services/cr/updatestillbirth",
  },
  crnacbirth: {
    create: "/birth-services/cr/createnac",
    search: "/birth-services/cr/searchnac",
    update: "/birth-services/cr/updatenac",
    registry_download: "/birth-services/cr/registrynac/_download",
    registry_search_nac_birth: "/birth-services/cr/searchnac",
  },
  crbornoutsideindiabirth: {
    create: "/birth-services/cr/createbornoutside",
    search: "/birth-services/cr/searchbornoutside",
    update: "/birth-services/cr/updatebornoutside",
  },
  crabandonedbirth: {
    create: "/birth-services/cr/createabandoned",
    search: "/birth-services/cr/searchabandoned",
    update: "/birth-services/cr/updateabandoned",
  },
  crnacdeath: {
    create: "/death-services/v1/deathdetails/_createdeathnac",
    update: "/death-services/v1/deathdetails/_updatedeathnac",
    search: "/death-services/v1/deathdetails/_searchdeathnac",
    registry_download: "/death-services/v1/deathregistry/_downloaddeathnac",
    registry_search_nac_death: "/death-services/v1/deathregistry/_searchdeathnac",
  },
  crdeath: {
    create: "/death-services/v1/deathdetails/_createdeath",
    search: "/death-services/v1/deathdetails/_searchdeath",
    download_pdf: "/egov-pdf/download/CR/",
    update: "/death-services/v1/deathdetails/_updatedeath",
    registry_search: "/death-services/v1/deathregistry/_searchdeath",
    registry_download: "/death-services/v1/deathregistry/_downloaddeath",
    correct_update: "/death-services/v1/deathdetails/createdeathcorrection",
  },
  crabandoneddeath: {
    create: "/death-services/v1/deathdetails/_createdeathabandoned",
    search: "/death-services/v1/deathdetails/_searchdeathabandoned",
    download_pdf: "/egov-pdf/download/CR/",
    update: "/death-services/v1/deathdetails/_updatedeathabandoned",
    registry_search: "/death-services/v1/deathregistry/_searchdeathabandoned",
    registry_download: "/death-services/v1/deathregistry/_downloaddeath",
  },
  crmarriage: {
    create: "/marriage-services/v1/marriagedetails/_createmarriage",
    search: "/marriage-services/v1/marriagedetails/_searchmarriage",
    download_pdf: "/egov-pdf/download/CR/",
    update: "/marriage-services/v1/marriagedetails/_updatemarriage",
    registry_search_marriage: "/marriage-services/v1/marriagedetails/_searchregistry",
    correct_update: "/marriage-services/v1/marriagedetails/_createmarriagecorrection",
    registry_download: "/marriage-services/v1/marriagedetails/_certificate",
  },
  dfm: {
    create: "/filemgmnt/v1/applicantservices/_create",
    search: "/filemgmnt/v1/applicantpersonals/_search",
    download_pdf: "/egov-pdf/download/dfm/",
    update: "/filemgmnt/v1/applicantpersonals/_update",
    create_draft: "/filemgmnt/v1/draftfiles/_create",
    // create_draft: "/filemgmnt/v1/applicantservices/_createDraftingMain",
    create_note: "/filemgmnt/v1/applicantservices/_createDraftProcessInstance",
    fetch_draft: "/filemgmnt/v1/draftfiles/_search",
    // fetch_draft: "/filemgmnt/v1/applicantservices/_searchDrafting",
    arising_file: "/filemgmnt/v1/applicantservices/_createArisingFile",
    createmodule: "/filemgmnt/v1/masterdata/modules/_create",
    updatemodule: "/filemgmnt/v1/masterdata/modules/_update",
    updatesubfunct: "/filemgmnt/v1/masterdata/subfunctions/_update",
    updatemajor: "/filemgmnt/v1/masterdata/majorfunctions/_update",
    updateservice: "/filemgmnt/v1/masterdata/services/_update",
    deleteModule: "/filemgmnt/v1/masterdata/modules/_delete",
    deleteService: "/filemgmnt/v1/masterdata/services/_delete",
    deleteSubFunct: "/filemgmnt/v1/masterdata/subfunctions/_delete",
    deleteMajor: "/filemgmnt/v1/masterdata/majorfunctions/_delete",
    submodulesearch: "/filemgmnt/v1/masterdata/subfunctions/_search",
    modulesearch: "/filemgmnt/v1/masterdata/modules/_search",
    servicesearch: "/filemgmnt/v1/masterdata/services/_search",
    majorFunctionSearch: "/filemgmnt/v1/masterdata/majorfunctions/_search",
    createsubmodule: "/filemgmnt/v1/masterdata/subfunctions/_create",
    arising_file: "/filemgmnt/v1/arisingfiles/_create",
    majorFunction: "/filemgmnt/v1/masterdata/majorfunctions/_create",
    serviceAdding: "/filemgmnt/v1/masterdata/services/_create",
  },

  receipts: {
    receipt_download: "/egov-pdf/download/PAYMENT/consolidatedreceipt",
    payments: "/collection-services/payments",
    count: "/egov-hrms/employees/_count",
  },
  obps: {
    scrutinyDetails: "/edcr/rest/dcr/scrutinydetails",
    comparisionReport: "/edcr/rest/dcr/occomparison",
    create: "/bpa-services/v1/bpa/_create",
    nocSearch: "/noc-services/v1/noc/_search",
    updateNOC: "/noc-services/v1/noc/_update",
    update: "/bpa-services/v1/bpa/_update",
    bpaSearch: "/bpa-services/v1/bpa/_search",
    bpaRegSearch: "/tl-services/v1/BPAREG/_search",
    bpaRegCreate: "/tl-services/v1/BPAREG/_create",
    bpaRegGetBill: "/tl-calculator/v1/BPAREG/_getbill",
    bpaRegUpdate: "/tl-services/v1/BPAREG/_update",
    receipt_download: "/egov-pdf/download/PAYMENT/consolidatedreceipt",
    edcrreportdownload: "/bpa-services/v1/bpa/_permitorderedcr",
  },

  edcr: {
    create: "/edcr/rest/dcr/scrutinize",
  },

  events: {
    search: "/egov-user-event/v1/events/_search",
    update: "/egov-user-event/v1/events/lat/_update",
    updateEvent: "/egov-user-event/v1/events/_update",
    updateEventCDG: "/egov-user-event/v1/events/lat/_update",
    count: "/egov-user-event/v1/events/notifications/_count",
    create: "/egov-user-event/v1/events/_create",
  },

  ws: {
    water_search: "/ws-services/wc/_search",
    sewarage_search: "/sw-services/swc/_search",
  },

  engagement: {
    document: {
      search: "/egov-document-uploader/egov-du/document/_search",
      create: "/egov-document-uploader/egov-du/document/_create",
      delete: "/egov-document-uploader/egov-du/document/_delete",
      update: "/egov-document-uploader/egov-du/document/_update",
    },
    surveys: {
      create: "/egov-survey-services/egov-ss/survey/_create",
      update: "/egov-survey-services/egov-ss/survey/_update",
      search: "/egov-survey-services/egov-ss/survey/_search",
      delete: "/egov-survey-services/egov-ss/survey/_delete",
      submitResponse: "/egov-survey-services/egov-ss/survey/response/_submit",
      showResults: "/egov-survey-services/egov-ss/survey/response/_results",
    },
  },

  noc: {
    nocSearch: "/noc-services/v1/noc/_search",
  },
};
export default Urls;
