

CREATE TABLE IF NOT EXISTS eg_death_nac_registry
(
    id character varying(64)  NOT NULL, 
    tenantid character varying(50)  NOT NULL,
    dateofdeath bigint,    
    deceased_firstname_en character varying(64) ,
    deceased_firstname_ml character varying(64) ,
    deceased_middlename_en character varying(64) ,
    deceased_middlename_ml character varying(64) ,
    deceased_lastname_en character varying(64) ,
    deceased_lastname_ml character varying(64) ,
    deceased_aadhar_number character varying(500) ,
    deceased_gender character varying(64) ,	
    death_place character varying(64) ,
    death_place_inst_type character varying(64) ,
    death_place_inst_id character varying(64) ,   
	vehicle_hospital_en character varying(200) ,
    vehicle_fromplace_ml character varying(200) ,
    vehicle_fromplace_en character varying(200) ,
    vehicle_toplace_ml character varying(200) ,
    vehicle_toplace_en character varying(200) ,
    vehicle_number character varying(64) ,
	vehicle_first_halt character varying(200) ,
	vehicle_first_halt_ml character varying(200) ,	
    death_place_ward_id character varying(64) ,    
	death_place_locality_en character varying(200) ,
    death_place_locality_ml character varying(200) ,
    death_place_street_en character varying(200) ,
    death_place_street_ml character varying(200) ,          
	death_home_locality_en character varying(200) ,
    death_home_locality_ml character varying(200) ,
    death_home_street_en character varying(200) ,
    death_home_street_ml character varying(200) ,
    death_home_housename_en character varying(500) ,
    death_home_housename_ml character varying(500) ,
    death_home_postoffice_id character varying(200) ,
    death_home_pincode character varying(50) ,
    death_home_ward character varying(200) ,
	place_of_burial_en character varying(200) ,
	father_name_en character varying(64) ,
    father_name_ml character varying(64) ,
    father_aadharno character varying(500) ,
    mother_name_en character varying(64) ,
    mother_name_ml character varying(64) ,
    mother_aadharno character varying(500) ,  
    spouse_unavailable boolean,
    spouse_type character varying(64) ,
	spouse_name_en character varying(64) ,
    spouse_name_ml character varying(64) ,
    spouse_aadhaar character varying(500) ,	
	applicant_name character varying(200) ,
	applicant_aadhar_no character varying(500) ,
	applicant_relation character varying(64) ,
	applicant_address character varying(500) ,
	applicant_mobile_no bigint,
	applicant_email character varying(200) ,	
    status character varying(64) ,
    created_by character varying(64) ,
    createdtime bigint,
    lastmodifiedby character varying(64) ,
    lastmodifiedtime bigint,
    workflowcode character varying(64) ,
    businessservice character varying(64) ,
    action character varying(64) ,
    comment character varying(64) ,
    assignee character varying(64) ,
    appl_type character varying(64) ,
	ack_no character varying(64) ,
    application_date bigint,
    funcion_uid character varying(64) ,    
    certificate_no character varying(64),
    certificate_date bigint,
	certificate_no_id bigint,
    filestoreid character varying(64);	
    dateofissue bigint;
    CONSTRAINT eg_death_nac_registry_pkey PRIMARY KEY (id)
);
