--Create Death Services Tables by Rakhi S IKM
-- Table1: public.eg_death_dtls
CREATE TABLE IF NOT EXISTS public.eg_death_dtls
(
    id character varying(64) NOT NULL,
    registrationunit character varying(64),
    tenantid character varying(50) NOT NULL,
    death_date_unavailable boolean,
    dateofdeath bigint,
    time_of_death integer,
    timeofdeath_unit character varying(50),
    date_of_death_to bigint,
    time_of_death_to integer,
    timeofdeath_unit_to character varying(50),
    deceased_unidentified smallint,
    deceased_title character varying(64),
    deceased_firstname_en character varying(64),
    deceased_firstname_ml character varying(64),
    deceased_middlename_en character varying(64),
    deceased_middlename_ml character varying(64),
    deceased_lastname_en character varying(64),
    deceased_lastname_ml character varying(64),
    deceased_aadhar_number character varying(500),
    deceased_gender character varying(64),
    age integer,
    age_unit character varying(64),
    dateofbirth bigint,
    death_place character varying(64),
    death_place_inst_type character varying(64),
    death_place_inst_id character varying(64),
    death_place_officer_name character varying(200),
    death_place_other_ml character varying(500),
    death_place_other_en character varying(200),
    informant_title character varying(64),
    informant_name_en character varying(64),
    informant_name_ml character varying(64),
    informant_aadhar_submitted boolean,
    informant_aadhar_no character varying(500),
    informant_mobile_no bigint,
    general_remarks character varying(500),
    status character varying(64),
    submitted_on bigint,
    created_by character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    burial_district character varying(64),
    burial_lbtype character varying(64),
    burial_lbname character varying(64),
    registration_no character varying(64),
    ip_no character varying(64),
    op_no character varying(64),
    male_dependent_type character varying(64),
    male_dependent_title character varying(64),
    male_dependent_name_en character varying(64),
    male_dependent_name_ml character varying(64),
    male_dependent_aadharno character varying(500),
    male_dependent_mobileno character varying(64),
    male_dependent_mailid character varying(64),
    female_dependent_type character varying(64),
    female_dependent_title character varying(64),
    female_dependent_name_en character varying(64),
    female_dependent_name_ml character varying(64),
    female_dependent_aadharno character varying(500),
    female_dependent_mobileno character varying(64),
    female_dependent_mailid character varying(64),
    isvehicle smallint,
    vehicle_hospital_ml character varying(200),
    vehicle_hospital_en character varying(200),
    vehicle_fromplace_ml character varying(200),
    vehicle_fromplace_en character varying(200),
    vehicle_toplace_ml character varying(200),
    vehicle_toplace_en character varying(200),
    vehicle_number character varying(64),
    death_place_ward_id character varying(64),
    informant_age character varying(64),
    vehicle_driver_licenceno character varying(64),
    death_signed_officer_designation character varying(64),
    death_place_officer_mobile character varying(64),
    death_place_officer_aadhaar character varying(500),
    deceased_idprooftype character varying(64),
    application_no character varying(64),
    file_no character varying(64),
    ack_no character varying(64),
    workflowcode character varying(64),
    businessservice character varying(64),
    action character varying(64),
    comment character varying(64),
    assignee character varying(64),
    registration_date bigint,
    registration_no_id bigint,
    appl_type character varying(64),
    deceased_idproofno character varying(500),
    kiosk_id bigint,
    burial_state character varying(64),
    vehicle_first_halt character varying(200),
    male_dependent_unavailable boolean,
    female_dependent_unavailable boolean,
    spouse_name_en character varying(64),
    spouse_name_ml character varying(64),
    spouse_unavailable boolean,
    spouse_emailid character varying(64),
    spouse_aadhaar character varying(500),
    spouse_mobileno character varying(64),
    spouse_type character varying(64),
    funcion_uid character varying(64),
    ack_no_id bigint,
    application_date bigint,
    other_vehicle_type character varying(64),
    deceased_aadhar_unavailable boolean,
    vehicle_first_halt_ml character varying(200),
    death_place_locality_en character varying(200),
    death_place_locality_ml character varying(200),
    death_place_street_en character varying(200),
    death_place_street_ml character varying(200),
    death_place_country character varying(200),
    death_place_state character varying(200),
    death_place_district character varying(200),
    death_place_city character varying(200),
    death_place_remarks_en character varying(500),
    death_place_remarks_ml character varying(500),
    place_of_burial_en character varying(200),
    place_of_burial_ml character varying(200),
    death_home_locality_en character varying(200),
    death_home_locality_ml character varying(200),
    death_home_street_en character varying(200),
    death_home_street_ml character varying(200),
    death_home_housename_en character varying(500),
    death_home_housename_ml character varying(500),
    death_home_postoffice_id character varying(200),
    death_home_postofficename_en character varying(200),
    death_home_postofficename_ml character varying(200),
    death_home_pincode character varying(50),
    death_home_ward character varying(200),
    death_home_taluk_id character varying(200),
    death_home_taluk_en character varying(500),
    death_home_taluk_ml character varying(500),
    family_mobile_no bigint,
    family_email character varying(200),
    initiator_name character varying(200),
    initiator_aadhar_submitted boolean,
    initiator_aadhar_no character varying(500),
    initiator_mobile_no bigint,
    initiator_relation character varying(64),
    informant_address character varying(500),
    initiator_address character varying(500),
    is_declaration_initiator boolean,
    is_declaration_informant boolean,
    burial_lb_ward character varying(200),
    burial_description character varying(500),
    deceased_description character varying(500),
    informant_office character varying(200),
    informant_designation character varying(200),
    informant_pen_no character varying(200),
    informant_office_address character varying(1000),
    aadhar_corrflag boolean,
    name_corrflag boolean,
    deathdate_corrflag boolean,
    deathplace_corrflag boolean,
    gender_corrflag boolean,
    mother_corrflag boolean,
    father_corrflag boolean,
    spouse_corrflag boolean,
    presentaddr_corrflag boolean,
    permanentaddr_corrflag boolean,
    previous_ack_no character varying(100),
    initiator_email character varying(200),
    normal_regn boolean,
    delayed_within_thirty boolean,
    delayed_within_oneyear boolean,
    delayed_after_oneyear boolean,
    CONSTRAINT eg_death_dtls_pkey1 PRIMARY KEY (id)
);
-- Table2: public.eg_death_dtls_log

CREATE TABLE IF NOT EXISTS public.eg_death_dtls_log
(
    id character varying(64) NOT NULL,
    registrationunit character varying(64),
    tenantid character varying(50) NOT NULL,
    death_date_unavailable boolean,
    dateofdeath bigint,
    time_of_death integer,
    timeofdeath_unit character varying(50),
    date_of_death_to bigint,
    time_of_death_to integer,
    timeofdeath_unit_to character varying(50),
    deceased_unidentified smallint,
    deceased_title character varying(64),
    deceased_firstname_en character varying(64),
    deceased_firstname_ml character varying(64),
    deceased_middlename_en character varying(64),
    deceased_middlename_ml character varying(64),
    deceased_lastname_en character varying(64),
    deceased_lastname_ml character varying(64),
    deceased_aadhar_number character varying(500),
    deceased_gender character varying(64),
    age integer,
    age_unit character varying(64),
    dateofbirth bigint,
    death_place character varying(64),
    death_place_inst_type character varying(64),
    death_place_inst_id character varying(64),
    death_place_officer_name character varying(200),
    death_place_other_ml character varying(500),
    death_place_other_en character varying(200),
    informant_title character varying(64),
    informant_name_en character varying(64),
    informant_name_ml character varying(64),
    informant_aadhar_submitted boolean,
    informant_aadhar_no character varying(500),
    informant_mobile_no bigint,
    general_remarks character varying(500),
    status character varying(64),
    submitted_on bigint,
    created_by character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    burial_district character varying(64),
    burial_lbtype character varying(64),
    burial_lbname character varying(64),
    registration_no character varying(64),
    ip_no character varying(64),
    op_no character varying(64),
    male_dependent_type character varying(64),
    male_dependent_title character varying(64),
    male_dependent_name_en character varying(64),
    male_dependent_name_ml character varying(64),
    male_dependent_aadharno character varying(500),
    male_dependent_mobileno character varying(64),
    male_dependent_mailid character varying(64),
    female_dependent_type character varying(64),
    female_dependent_title character varying(64),
    female_dependent_name_en character varying(64),
    female_dependent_name_ml character varying(64),
    female_dependent_aadharno character varying(500),
    female_dependent_mobileno character varying(64),
    female_dependent_mailid character varying(64),
    isvehicle smallint,
    vehicle_hospital_ml character varying(200),
    vehicle_hospital_en character varying(200),
    vehicle_fromplace_ml character varying(200),
    vehicle_fromplace_en character varying(200),
    vehicle_toplace_ml character varying(200),
    vehicle_toplace_en character varying(200),
    vehicle_number character varying(64),
    death_place_ward_id character varying(64),
    informant_age character varying(64),
    vehicle_driver_licenceno character varying(64),
    death_signed_officer_designation character varying(64),
    death_place_officer_mobile character varying(64),
    death_place_officer_aadhaar character varying(500),
    deceased_idprooftype character varying(64),
    application_no character varying(64),
    file_no character varying(64),
    ack_no character varying(64),
    workflowcode character varying(64),
    businessservice character varying(64),
    action character varying(64),
    comment character varying(64),
    assignee character varying(64),
    registration_date bigint,
    registration_no_id bigint,
    appl_type character varying(64),
    deceased_idproofno character varying(500),
    kiosk_id bigint,
    burial_state character varying(64),
    vehicle_first_halt character varying(200),
    male_dependent_unavailable boolean,
    female_dependent_unavailable boolean,
    spouse_name_en character varying(64),
    spouse_name_ml character varying(64),
    spouse_unavailable boolean,
    spouse_emailid character varying(64),
    spouse_aadhaar character varying(500),
    spouse_mobileno character varying(64),
    spouse_type character varying(64),
    funcion_uid character varying(64),
    ack_no_id bigint,
    application_date bigint,
    other_vehicle_type character varying(64),
    deceased_aadhar_unavailable boolean,
    vehicle_first_halt_ml character varying(200),
    death_place_locality_en character varying(200),
    death_place_locality_ml character varying(200),
    death_place_street_en character varying(200),
    death_place_street_ml character varying(200),
    death_place_country character varying(200),
    death_place_state character varying(200),
    death_place_district character varying(200),
    death_place_city character varying(200),
    death_place_remarks_en character varying(500),
    death_place_remarks_ml character varying(500),
    place_of_burial_en character varying(200),
    place_of_burial_ml character varying(200),
    death_home_locality_en character varying(200),
    death_home_locality_ml character varying(200),
    death_home_street_en character varying(200),
    death_home_street_ml character varying(200),
    death_home_housename_en character varying(500),
    death_home_housename_ml character varying(500),
    death_home_postoffice_id character varying(200),
    death_home_postofficename_en character varying(200),
    death_home_postofficename_ml character varying(200),
    death_home_pincode character varying(50),
    death_home_ward character varying(200),
    death_home_taluk_id character varying(200),
    death_home_taluk_en character varying(500),
    death_home_taluk_ml character varying(500),
    family_mobile_no bigint,
    family_email character varying(200),
    initiator_name character varying(200),
    initiator_aadhar_submitted boolean,
    initiator_aadhar_no character varying(500),
    initiator_mobile_no bigint,
    initiator_relation character varying(64),
    informant_address character varying(500),
    initiator_address character varying(500),
    is_declaration_initiator boolean,
    is_declaration_informant boolean,
    burial_lb_ward character varying(200),
    burial_description character varying(500),
    deceased_description character varying(500),
    informant_office character varying(200),
    informant_designation character varying(200),
    informant_pen_no character varying(200),
    informant_office_address character varying(1000),
    aadhar_corrflag boolean,
    name_corrflag boolean,
    deathdate_corrflag boolean,
    deathplace_corrflag boolean,
    gender_corrflag boolean,
    mother_corrflag boolean,
    father_corrflag boolean,
    spouse_corrflag boolean,
    presentaddr_corrflag boolean,
    permanentaddr_corrflag boolean,
    previous_ack_no character varying(100),
    initiator_email character varying(200),
    normal_regn boolean,
    delayed_within_thirty boolean,
    delayed_within_oneyear boolean,
    delayed_after_oneyear boolean
);
-- Table3: public.eg_death_address_dtls

CREATE TABLE IF NOT EXISTS public.eg_death_address_dtls
(
    id character varying(64) NOT NULL,
    death_dtl_id character varying(64),
    tenantid character varying(50) NOT NULL,
    addr_typeid character varying(50),
    house_no character varying(100),
    residence_assc_no character varying(100),
    streetname_en character varying(200),
    streetname_ml character varying(200),
    locality_en character varying(200),
    locality_ml character varying(200),
    city_en character varying(200),
    city_ml character varying(200),
    ward_id character varying(100),
    taluk_id character varying(100),
    village_id character varying(200),
    postoffice_id character varying(200),
    pincode character varying(50),
    district_id character varying(100),
    state_id character varying(100),
    country_id character varying(100),
    taluk_name_en character varying(200),
    taluk_name_ml character varying(200),
    village_name_en character varying(200),
    village_name_ml character varying(200),
    postoffice_name_en character varying(200),
    postoffice_name_ml character varying(200),
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    location_type character varying(150),
    housename_ml character varying(500),
    housename_en character varying(500),
    lbtype character varying(200),
    postal_code character varying(200),
    province_name_en character varying(200),
    province_name_ml character varying(200),
    city_town_village character varying(200),
    addr_lb_name character varying(200),
    addr_sameas_present boolean,
    CONSTRAINT eg_death_address_dtls_pkey PRIMARY KEY (id),
    CONSTRAINT fk_eg_death_dtls FOREIGN KEY (death_dtl_id)
        REFERENCES public.eg_death_dtls (id)
);
-- Table4: public.eg_death_address_dtls_log

CREATE TABLE IF NOT EXISTS public.eg_death_address_dtls_log
(
    id character varying(64) NOT NULL,
    death_dtl_id character varying(64),
    tenantid character varying(50) NOT NULL,
    addr_typeid character varying(50),
    house_no character varying(100),
    residence_assc_no character varying(100),
    streetname_en character varying(200),
    streetname_ml character varying(200),
    locality_en character varying(200),
    locality_ml character varying(200),
    city_en character varying(200),
    city_ml character varying(200),
    ward_id character varying(100),
    taluk_id character varying(100),
    village_id character varying(200),
    postoffice_id character varying(200),
    pincode character varying(50),
    district_id character varying(100),
    state_id character varying(100),
    country_id character varying(100),
    taluk_name_en character varying(200),
    taluk_name_ml character varying(200),
    village_name_en character varying(200),
    village_name_ml character varying(200),
    postoffice_name_en character varying(200),
    postoffice_name_ml character varying(200),
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    location_type character varying(64),
    housename_ml character varying(500),
    housename_en character varying(500),
    lbtype character varying(200),
    postal_code character varying(200),
    province_name_en character varying(200),
    province_name_ml character varying(200),
    city_town_village character varying(200),
    addr_lb_name character varying(200),
    addr_sameas_present boolean
);
-- Table5: public.eg_death_statistical_dtls

CREATE TABLE IF NOT EXISTS public.eg_death_statistical_dtls
(
    id character varying(64) NOT NULL,
    death_dtl_id character varying(64),
    tenantid character varying(50) NOT NULL,
    residencelocalbody character varying(75),
    residence_place_type character varying(200),
    residencedistrict character varying(250),
    residencestate character varying(100),
    religion character varying(200),
    religion_other character varying(100),
    occupation character varying(100),
    occupation_other character varying(500),
    medical_attention_type character varying(500),
    death_medically_certified character varying(50),
    death_cause_main character varying(200),
    death_cause_sub character varying(200),
    death_cause_other character varying(200),
    death_during_delivery character varying(200),
    smoking_num_years integer,
    tobacco_num_years integer,
    arecanut_num_years integer,
    alcohol_num_years integer,
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    nationality character varying(200),
    occupation_sub character varying(200),
    occupation_minor character varying(200),
    education_main character varying(200),
    education_sub character varying(200),
    residencelbtype character varying(64),
    smoking_type character varying(64),
    tobacco_type character varying(64),
    arecanut_type integer,
    alcohol_type character varying(64),
    autopsy_performed character varying(50),
    autopsy_completed character varying(50),
    manner_of_death character varying(200),
    death_cause_main_custom character varying(200),
    death_cause_main_interval integer,
    death_cause_main_timeunit character varying(200),
    death_cause_sub_custom character varying(200),
    death_cause_sub_interval integer,
    death_cause_sub_timeunit character varying(200),
    death_cause_sub2 character varying(200),
    death_cause_sub2_custom character varying(200),
    death_cause_sub2_interval integer,
    death_cause_sub2_timeunit character varying(200),
    deceased_pregnant character varying(200),
    is_delivery character varying(200),
    medical_practitioner_name character varying(200),
    medical_practitioner_aadhaar character varying(200),
    medical_practitioner_mobile bigint,
    medical_practitioner_regno character varying(200),
    medical_practitioner_desig character varying(200),
    medical_practitioner_address character varying(1000),
    CONSTRAINT eg_death_statistical_dtls_pkey PRIMARY KEY (id),
    CONSTRAINT fk_eg_death_dtls FOREIGN KEY (death_dtl_id)
        REFERENCES public.eg_death_dtls (id) 
);

-- Table6: public.eg_death_statistical_dtls_log

CREATE TABLE IF NOT EXISTS public.eg_death_statistical_dtls_log
(
    id character varying(64) NOT NULL,
    death_dtl_id character varying(64) NOT NULL,
    tenantid character varying(50) NOT NULL,
    residencelocalbody character varying(75),
    residence_place_type character varying(200),
    residencedistrict character varying(250),
    residencestate character varying(100),
    religion character varying(200),
    religion_other character varying(100),
    occupation character varying(100),
    occupation_other character varying(500),
    medical_attention_type character varying(500),
    death_medically_certified character varying(50),
    death_cause_main character varying(200),
    death_cause_sub character varying(200),
    death_cause_other character varying(200),
    death_during_delivery character varying(200),
    smoking_num_years integer,
    tobacco_num_years integer,
    arecanut_num_years integer,
    alcohol_num_years integer,
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    nationality character varying(200),
    occupation_sub character varying(200),
    occupation_minor character varying(200),
    education_main character varying(200),
    education_sub character varying(200),
    residencelbtype character varying(64),
    smoking_type character varying(64),
    tobacco_type character varying(64),
    arecanut_type integer,
    alcohol_type character varying(64),
    autopsy_performed character varying(50),
    autopsy_completed character varying(50),
    manner_of_death character varying(200),
    death_cause_main_custom character varying(200),
    death_cause_main_interval integer,
    death_cause_main_timeunit character varying(200),
    death_cause_sub_custom character varying(200),
    death_cause_sub_interval integer,
    death_cause_sub_timeunit character varying(200),
    death_cause_sub2 character varying(200),
    death_cause_sub2_custom character varying(200),
    death_cause_sub2_interval integer,
    death_cause_sub2_timeunit character varying(200),
    deceased_pregnant character varying(200),
    is_delivery character varying(200),
    medical_practitioner_name character varying(200),
    medical_practitioner_aadhaar character varying(200),
    medical_practitioner_mobile bigint,
    medical_practitioner_regno character varying(200),
    medical_practitioner_desig character varying(200),
    medical_practitioner_address character varying(1000)
);
-- Table7: public.eg_death_document_dtls

CREATE TABLE IF NOT EXISTS public.eg_death_document_dtls
(
    id character varying(64),
    tenantid character varying(50),
    document_type character varying(500),
    death_dtls_id character varying(64),
    filestore_id character varying(64),
    filename character varying(64),
    death_ackno character varying(64),
    documentuid character varying(64),
    active boolean,
    created_by character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    rdo_proceedings_no character varying(200),
    nac_registration_no character varying(200)
);
-- Table8: public.eg_death_dtls_registry

CREATE TABLE IF NOT EXISTS public.eg_death_dtls_registry
(
    id character varying(64) NOT NULL,
    registrationunit character varying(64),
    tenantid character varying(50) NOT NULL,
    death_date_unavailable boolean,
    dateofdeath bigint,
    time_of_death integer,
    timeofdeath_unit character varying(50),
    date_of_death_to bigint,
    time_of_death_to integer,
    timeofdeath_unit_to character varying(50),
    deceased_unidentified smallint,
    deceased_title character varying(50),
    deceased_firstname_en character varying(200),
    deceased_firstname_ml character varying(200),
    deceased_middlename_en character varying(200),
    deceased_middlename_ml character varying(200),
    deceased_lastname_en character varying(200),
    deceased_lastname_ml character varying(200),
    deceased_aadhar_number character varying(500),
    deceased_gender character varying(50),
    age integer,
    age_unit character varying(64),
    dateofbirth bigint,
    death_place character varying(200),
    death_place_inst_type character varying(200),
    death_place_inst_id character varying(200),
    death_place_officer_name character varying(200),
    death_place_other_ml character varying(500),
    death_place_other_en character varying(200),
    informant_title character varying(200),
    informant_name_en character varying(200),
    informant_name_ml character varying(200),
    informant_aadhar_submitted boolean,
    informant_aadhar_no character varying(500),
    informant_mobile_no bigint,
    general_remarks character varying(500),
    application_status character varying(150),
    submitted_on bigint,
    created_by character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    burial_district character varying(1000),
    burial_lbtype character varying(150),
    burial_lbname character varying(1000),
    registration_no character varying(200),
    ip_no character varying(200),
    op_no character varying(200),
    male_dependent_type character varying(200),
    male_dependent_title character varying(200),
    male_dependent_name_en character varying(200),
    male_dependent_name_ml character varying(200),
    male_dependent_aadharno character varying(500),
    male_dependent_mobileno character varying(150),
    male_dependent_mailid character varying(150),
    female_dependent_type character varying(200),
    female_dependent_title character varying(200),
    female_dependent_name_en character varying(200),
    female_dependent_name_ml character varying(200),
    female_dependent_aadharno character varying(500),
    female_dependent_mobileno character varying(150),
    female_dependent_mailid character varying(150),
    isvehicle smallint,
    vehicle_hospital_ml character varying(500),
    vehicle_hospital_en character varying(500),
    vehicle_fromplace_ml character varying(500),
    vehicle_fromplace_en character varying(500),
    vehicle_toplace_ml character varying(500),
    vehicle_toplace_en character varying(500),
    vehicle_number character varying(500),
    death_place_ward_id character varying(500),
    informant_age character varying(500),
    vehicle_driver_licenceno character varying(500),
    death_signed_officer_designation character varying(500),
    death_place_officer_mobile character varying(500),
    death_place_officer_aadhaar character varying(500),
    deceased_idprooftype character varying(500),
    application_no character varying(500),
    file_no character varying(500),
    ack_no character varying(500),
    dateofreport bigint,
    registration_date bigint,
    registration_no_id bigint,
    deceased_idproofno character varying(500),
    bad_record smallint,
    record_no character varying(20),
    f12_no character varying(20),
    f12_issued smallint,
    book_no character varying(20),
    is_migrated smallint,
    migration_date bigint,
    kiosk_id bigint,
    burial_state character varying(64),
    vehicle_first_halt character varying(200),
    male_dependent_unavailable boolean,
    female_dependent_unavailable boolean,
    spouse_name_en character varying(64),
    spouse_name_ml character varying(64),
    spouse_unavailable boolean,
    spouse_emailid character varying(64),
    spouse_aadhaar character varying(500),
    spouse_mobileno character varying(64),
    spouse_type character varying(64),
    funcion_uid character varying(64),
    certificate_no_id bigint,
    certificate_no character varying(64),
    certificate_date bigint,
    other_vehicle_type character varying(64),
    deceased_aadhar_unavailable boolean,
    vehicle_first_halt_ml character varying(200),
    death_place_locality_en character varying(200),
    death_place_locality_ml character varying(200),
    death_place_street_en character varying(200),
    death_place_street_ml character varying(200),
    death_place_country character varying(200),
    death_place_state character varying(200),
    death_place_district character varying(200),
    death_place_city character varying(200),
    death_place_remarks_en character varying(500),
    death_place_remarks_ml character varying(500),
    place_of_burial_en character varying(200),
    place_of_burial_ml character varying(200),
    death_home_locality_en character varying(200),
    death_home_locality_ml character varying(200),
    death_home_street_en character varying(200),
    death_home_street_ml character varying(200),
    death_home_housename_en character varying(500),
    death_home_housename_ml character varying(500),
    death_home_postoffice_id character varying(200),
    death_home_postofficename_en character varying(200),
    death_home_postofficename_ml character varying(200),
    death_home_pincode character varying(50),
    death_home_ward character varying(200),
    death_home_taluk_id character varying(200),
    death_home_taluk_en character varying(500),
    death_home_taluk_ml character varying(500),
    family_mobile_no bigint,
    family_email character varying(200),
    informant_address character varying(500),
    initiator_address character varying(500),
    is_declaration_initiator boolean,
    is_declaration_informant boolean,
    burial_lb_ward character varying(200),
    burial_description character varying(500),
    deceased_description character varying(500),
    informant_office character varying(200),
    informant_designation character varying(200),
    informant_pen_no character varying(200),
    informant_office_address character varying(1000),
    initiator_email character varying(200),
    normal_regn boolean,
    delayed_within_thirty boolean,
    delayed_within_oneyear boolean,
    delayed_after_oneyear boolean,
    CONSTRAINT eg_death_dtls_registry_pkey PRIMARY KEY (id)
);

-- Table9: public.eg_death_dtls_registry_log

CREATE TABLE IF NOT EXISTS public.eg_death_dtls_registry_log
(
    id character varying(64) NOT NULL,
    registrationunit character varying(64),
    tenantid character varying(50) NOT NULL,
    death_date_unavailable boolean,
    dateofdeath bigint,
    time_of_death integer,
    timeofdeath_unit character varying(50),
    date_of_death_to bigint,
    time_of_death_to integer,
    timeofdeath_unit_to character varying(50),
    deceased_unidentified smallint,
    deceased_title character varying(50),
    deceased_firstname_en character varying(200),
    deceased_firstname_ml character varying(200),
    deceased_middlename_en character varying(200),
    deceased_middlename_ml character varying(200),
    deceased_lastname_en character varying(200),
    deceased_lastname_ml character varying(200),
    deceased_aadhar_number character varying(500),
    deceased_gender character varying(50),
    age integer,
    age_unit character varying(64),
    dateofbirth bigint,
    death_place character varying(200),
    death_place_inst_type character varying(200),
    death_place_inst_id character varying(200),
    death_place_officer_name character varying(200),
    death_place_other_ml character varying(500),
    death_place_other_en character varying(200),
    informant_title character varying(200),
    informant_name_en character varying(200),
    informant_name_ml character varying(200),
    informant_aadhar_submitted boolean,
    informant_aadhar_no character varying(500),
    informant_mobile_no bigint,
    general_remarks character varying(500),
    application_status character varying(150),
    submitted_on bigint,
    created_by character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    burial_district character varying(1000),
    burial_lbtype character varying(150),
    burial_lbname character varying(1000),
    registration_no character varying(200),
    ip_no character varying(200),
    op_no character varying(200),
    male_dependent_type character varying(200),
    male_dependent_title character varying(200),
    male_dependent_name_en character varying(200),
    male_dependent_name_ml character varying(200),
    male_dependent_aadharno character varying(500),
    male_dependent_mobileno character varying(150),
    male_dependent_mailid character varying(150),
    female_dependent_type character varying(200),
    female_dependent_title character varying(200),
    female_dependent_name_en character varying(200),
    female_dependent_name_ml character varying(200),
    female_dependent_aadharno character varying(500),
    female_dependent_mobileno character varying(150),
    female_dependent_mailid character varying(150),
    isvehicle smallint,
    vehicle_hospital_ml character varying(500),
    vehicle_hospital_en character varying(500),
    vehicle_fromplace_ml character varying(500),
    vehicle_fromplace_en character varying(500),
    vehicle_toplace_ml character varying(500),
    vehicle_toplace_en character varying(500),
    vehicle_number character varying(500),
    death_place_ward_id character varying(500),
    informant_age character varying(500),
    vehicle_driver_licenceno character varying(500),
    death_signed_officer_designation character varying(500),
    death_place_officer_mobile character varying(500),
    death_place_officer_aadhaar character varying(500),
    deceased_idprooftype character varying(500),
    application_no character varying(500),
    file_no character varying(500),
    ack_no character varying(500),
    dateofreport bigint,
    registration_date bigint,
    registration_no_id bigint,
    deceased_idproofno character varying(500),
    bad_record smallint,
    record_no character varying(20),
    f12_no character varying(20),
    f12_issued smallint,
    book_no character varying(20),
    is_migrated smallint,
    migration_date bigint,
    kiosk_id bigint,
    burial_state character varying(64),
    vehicle_first_halt character varying(200),
    male_dependent_unavailable boolean,
    female_dependent_unavailable boolean,
    spouse_name_en character varying(64),
    spouse_name_ml character varying(64),
    spouse_unavailable boolean,
    spouse_emailid character varying(64),
    spouse_aadhaar character varying(500),
    spouse_mobileno character varying(64),
    spouse_type character varying(64),
    funcion_uid character varying(64),
    certificate_no_id bigint,
    certificate_no character varying(64),
    certificate_date bigint,
    other_vehicle_type character varying(64),
    deceased_aadhar_unavailable boolean,
    vehicle_first_halt_ml character varying(200),
    death_place_locality_en character varying(200),
    death_place_locality_ml character varying(200),
    death_place_street_en character varying(200),
    death_place_street_ml character varying(200),
    death_place_country character varying(200),
    death_place_state character varying(200),
    death_place_district character varying(200),
    death_place_city character varying(200),
    death_place_remarks_en character varying(500),
    death_place_remarks_ml character varying(500),
    place_of_burial_en character varying(200),
    place_of_burial_ml character varying(200),
    death_home_locality_en character varying(200),
    death_home_locality_ml character varying(200),
    death_home_street_en character varying(200),
    death_home_street_ml character varying(200),
    death_home_housename_en character varying(500),
    death_home_housename_ml character varying(500),
    death_home_postoffice_id character varying(200),
    death_home_postofficename_en character varying(200),
    death_home_postofficename_ml character varying(200),
    death_home_pincode character varying(50),
    death_home_ward character varying(200),
    death_home_taluk_id character varying(200),
    death_home_taluk_en character varying(500),
    death_home_taluk_ml character varying(500),
    family_mobile_no bigint,
    family_email character varying(200),
    informant_address character varying(500),
    initiator_address character varying(500),
    is_declaration_initiator boolean,
    is_declaration_informant boolean,
    burial_lb_ward character varying(200),
    burial_description character varying(500),
    deceased_description character varying(500),
    informant_office character varying(200),
    informant_designation character varying(200),
    informant_pen_no character varying(200),
    informant_office_address character varying(1000),
    initiator_email character varying(200),
    normal_regn boolean,
    delayed_within_thirty boolean,
    delayed_within_oneyear boolean,
    delayed_after_oneyear boolean
);

-- Table10: public.eg_death_nac_registry

CREATE TABLE IF NOT EXISTS public.eg_death_nac_registry
(
    id character varying(64)  NOT NULL,
    tenantid character varying(50)  NOT NULL,
    dateofdeath bigint,
    deceased_firstname_en character varying(64) ,
    deceased_firstname_ml character varying(64) ,
    deceased_middlename_en character varying(64) ,
    deceased_middlename_ml character varying(64) ,
    deceased_lastname_en character varying(64) ,
    deceased_lastname_ml character varying(64) ,
    deceased_aadhar_number character varying(500) ,
    deceased_gender character varying(64) ,
    death_place character varying(64) ,
    death_place_inst_type character varying(64) ,
    death_place_inst_id character varying(64) ,
    vehicle_hospital_en character varying(200) ,
    vehicle_fromplace_ml character varying(200) ,
    vehicle_fromplace_en character varying(200) ,
    vehicle_toplace_ml character varying(200) ,
    vehicle_toplace_en character varying(200) ,
    vehicle_number character varying(64) ,
    vehicle_first_halt character varying(200) ,
    vehicle_first_halt_ml character varying(200) ,
    death_place_ward_id character varying(64) ,
    death_place_locality_en character varying(200) ,
    death_place_locality_ml character varying(200) ,
    death_place_street_en character varying(200) ,
    death_place_street_ml character varying(200) ,
    death_home_locality_en character varying(200) ,
    death_home_locality_ml character varying(200) ,
    death_home_street_en character varying(200) ,
    death_home_street_ml character varying(200) ,
    death_home_housename_en character varying(500) ,
    death_home_housename_ml character varying(500) ,
    death_home_postoffice_id character varying(200) ,
    death_home_pincode character varying(50) ,
    death_home_ward character varying(200) ,
    place_of_burial_en character varying(200) ,
    father_name_en character varying(64) ,
    father_name_ml character varying(64) ,
    father_aadharno character varying(500) ,
    mother_name_en character varying(64) ,
    mother_name_ml character varying(64) ,
    mother_aadharno character varying(500) ,
    spouse_unavailable boolean,
    spouse_type character varying(64) ,
    spouse_name_en character varying(64) ,
    spouse_name_ml character varying(64) ,
    spouse_aadhaar character varying(500) ,
    applicant_name character varying(200) ,
    applicant_aadhar_no character varying(500) ,
    applicant_relation character varying(64) ,
    applicant_address character varying(500) ,
    applicant_mobile_no bigint,
    applicant_email character varying(200) ,
    status character varying(64) ,
    created_by character varying(64) ,
    createdtime bigint,
    lastmodifiedby character varying(64) ,
    lastmodifiedtime bigint,
    workflowcode character varying(64) ,
    businessservice character varying(64) ,
    action character varying(64) ,
    comment character varying(64) ,
    assignee character varying(64) ,
    appl_type character varying(64) ,
    ack_no character varying(64) ,
    application_date bigint,
    funcion_uid character varying(64) ,
    certificate_no character varying(64) ,
    certificate_date bigint,
    certificate_no_id bigint,
    filestoreid character varying(200) ,
    dateofissue bigint,
    is_nac boolean,
    is_nia boolean,
    permanent_address character varying(1000) ,
    CONSTRAINT eg_death_nac_registry_pkey PRIMARY KEY (id)
);

-- Table 11: public.eg_death_address_registry

CREATE TABLE IF NOT EXISTS public.eg_death_address_registry
(
    id character varying(64) NOT NULL,
    death_dtl_id character varying(64),
    tenantid character varying(50) NOT NULL,
    addr_typeid character varying(50),
    house_no character varying(100),
    residence_assc_no character varying(100),
    streetname_en character varying(200),
    streetname_ml character varying(200),
    locality_en character varying(200),
    locality_ml character varying(200),
    city_en character varying(200),
    city_ml character varying(200),
    ward_id character varying(100),
    taluk_id character varying(100),
    village_id character varying(200),
    postoffice_id character varying(200),
    pincode character varying(50),
    district_id character varying(100),
    state_id character varying(100),
    country_id character varying(100),
    taluk_name_en character varying(200),
    taluk_name_ml character varying(200),
    village_name_en character varying(200),
    village_name_ml character varying(200),
    postoffice_name_en character varying(200),
    postoffice_name_ml character varying(200),
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    location_type character varying(150),
    housename_ml character varying(500),
    housename_en character varying(500),
    mig_ack_no character varying(64),
    lbtype character varying(200),
    postal_code character varying(200),
    province_name_en character varying(200),
    province_name_ml character varying(200),
    city_town_village character varying(200),
    addr_lb_name character varying(200),
    addr_sameas_present boolean,
    CONSTRAINT eg_death_address_registry_pkey PRIMARY KEY (id),
    CONSTRAINT fk_eg_death_address_registry FOREIGN KEY (death_dtl_id)
        REFERENCES public.eg_death_dtls_registry (id)
);

-- Table 12: public.eg_death_address_registry_log

CREATE TABLE IF NOT EXISTS public.eg_death_address_registry_log
(
    id character varying(64) NOT NULL,
    death_dtl_id character varying(64),
    tenantid character varying(50) NOT NULL,
    addr_typeid character varying(50),
    house_no character varying(100),
    residence_assc_no character varying(100),
    streetname_en character varying(200),
    streetname_ml character varying(200),
    locality_en character varying(200),
    locality_ml character varying(200),
    city_en character varying(200),
    city_ml character varying(200),
    ward_id character varying(100),
    taluk_id character varying(100),
    village_id character varying(200),
    postoffice_id character varying(200),
    pincode character varying(50),
    district_id character varying(100),
    state_id character varying(100),
    country_id character varying(100),
    taluk_name_en character varying(200),
    taluk_name_ml character varying(200),
    village_name_en character varying(200),
    village_name_ml character varying(200),
    postoffice_name_en character varying(200),
    postoffice_name_ml character varying(200),
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    location_type character varying(150),
    housename_ml character varying(500),
    housename_en character varying(500),
    mig_ack_no character varying(64),
    lbtype character varying(200),
    postal_code character varying(200),
    province_name_en character varying(200),
    province_name_ml character varying(200),
    city_town_village character varying(200),
    addr_lb_name character varying(200),
    addr_sameas_present boolean
);

-- Table 13: public.eg_death_statistical_registry

CREATE TABLE IF NOT EXISTS public.eg_death_statistical_registry
(
    id character varying(64) NOT NULL,
    death_dtl_id character varying(64),
    tenantid character varying(50) NOT NULL,
    residencelocalbody character varying(75),
    residence_place_type character varying(200),
    residencedistrict character varying(250),
    residencestate character varying(100),
    religion character varying(200),
    religion_other character varying(100),
    occupation character varying(100),
    occupation_other character varying(500),
    medical_attention_type character varying(500),
    death_medically_certified character varying(50),
    death_cause_main character varying(200),
    death_cause_sub character varying(200),
    death_cause_other character varying(200),
    death_during_delivery character varying(200),
    smoking_num_years integer,
    tobacco_num_years integer,
    arecanut_num_years integer,
    alcohol_num_years integer,
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    nationality character varying(200),
    occupation_sub character varying(200),
    occupation_minor character varying(200),
    education_main character varying(200),
    education_sub character varying(200),
    residencelbtype character varying(64),
    smoking_type character varying(64),
    tobacco_type character varying(64),
    arecanut_type integer,
    alcohol_type character varying(64),
    mig_ack_no character varying(64),
    autopsy_performed character varying(50),
    autopsy_completed character varying(50),
    manner_of_death character varying(200),
    death_cause_main_custom character varying(200),
    death_cause_main_interval integer,
    death_cause_main_timeunit character varying(200),
    death_cause_sub_custom character varying(200),
    death_cause_sub_interval integer,
    death_cause_sub_timeunit character varying(200),
    death_cause_sub2 character varying(200),
    death_cause_sub2_custom character varying(200),
    death_cause_sub2_interval integer,
    death_cause_sub2_timeunit character varying(200),
    deceased_pregnant character varying(200),
    is_delivery character varying(200),
    medical_practitioner_name character varying(200),
    medical_practitioner_aadhaar character varying(200),
    medical_practitioner_mobile bigint,
    medical_practitioner_regno character varying(200),
    medical_practitioner_desig character varying(200),
    medical_practitioner_address character varying(1000),
    CONSTRAINT eg_death_statistical_registry_pkey PRIMARY KEY (id),
    CONSTRAINT fk_eg_death_dtls_registry FOREIGN KEY (death_dtl_id)
        REFERENCES public.eg_death_dtls_registry (id)
);
-- Table 14: public.eg_death_statistical_registry_log

CREATE TABLE IF NOT EXISTS public.eg_death_statistical_registry_log
(
    id character varying(64) NOT NULL,
    death_dtl_id character varying(64),
    tenantid character varying(50) NOT NULL,
    residencelocalbody character varying(100),
    residence_place_type character varying(200),
    residencedistrict character varying(250),
    residencestate character varying(200),
    religion character varying(200),
    religion_other character varying(200),
    occupation character varying(200),
    occupation_other character varying(200),
    medical_attention_type character varying(500),
    death_medically_certified character varying(50),
    death_cause_main character varying(200),
    death_cause_sub character varying(200),
    death_cause_other character varying(200),
    death_during_delivery character varying(200),
    smoking_num_years integer,
    tobacco_num_years integer,
    arecanut_num_years integer,
    alcohol_num_years integer,
    createdby character varying(64),
    createdtime bigint,
    lastmodifiedby character varying(64),
    lastmodifiedtime bigint,
    nationality character varying(200),
    occupation_sub character varying(200),
    occupation_minor character varying(200),
    education_main character varying(200),
    education_sub character varying(200),
    residencelbtype character varying(64),
    smoking_type character varying(64),
    tobacco_type character varying(64),
    arecanut_type integer,
    alcohol_type character varying(64),
    mig_ack_no character varying(64),
    autopsy_performed character varying(50),
    autopsy_completed character varying(50),
    manner_of_death character varying(200),
    death_cause_main_custom character varying(200),
    death_cause_main_interval integer,
    death_cause_main_timeunit character varying(200),
    death_cause_sub_custom character varying(200),
    death_cause_sub_interval integer,
    death_cause_sub_timeunit character varying(200),
    death_cause_sub2 character varying(200),
    death_cause_sub2_custom character varying(200),
    death_cause_sub2_interval integer,
    death_cause_sub2_timeunit character varying(200),
    deceased_pregnant character varying(200),
    is_delivery character varying(200),
    medical_practitioner_name character varying(200),
    medical_practitioner_aadhaar character varying(200),
    medical_practitioner_mobile bigint,
    medical_practitioner_regno character varying(200),
    medical_practitioner_desig character varying(200),
    medical_practitioner_address character varying(1000)
);
-- Table 15: public.eg_death_cert_request

CREATE TABLE IF NOT EXISTS public.eg_death_cert_request
(
    id character varying(64) NOT NULL,
    ack_no character varying(64) NOT NULL,
    createdby character varying(64) NOT NULL,
    createdtime bigint NOT NULL,
    deathdtlid character varying(64) NOT NULL,
    filestoreid character varying(256),
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64),
    status character varying(64),
    additionaldetail jsonb,
    embeddedurl character varying(64),
    dateofissue bigint,
    counter integer,
    certificate_no character varying(64),
    CONSTRAINT eg_death_cert_request_registry_pkey PRIMARY KEY (id),
    CONSTRAINT eg_death_cert_request_registry_fkey FOREIGN KEY (deathdtlid)
        REFERENCES public.eg_death_dtls_registry (id)
);
-- Table16: public.eg_death_cert_request_audit

CREATE TABLE IF NOT EXISTS public.eg_death_cert_request_audit
(
    id character varying(64) NOT NULL,
    ack_no character varying(64) NOT NULL,
    createdby character varying(64) NOT NULL,
    createdtime bigint NOT NULL,
    deathdtlid character varying(64),
    filestoreid character varying(256),
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64),
    status character varying(64),
    additionaldetail jsonb,
    embeddedurl character varying(64),
    dateofissue bigint,
    counter integer,
    certificate_no character varying(64)
);
