-- Table: public.eg_death_dtls

-- DROP TABLE IF EXISTS public.eg_death_dtls;

CREATE TABLE IF NOT EXISTS public.eg_death_dtls
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    registrationunit character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    death_date_unavailable smallint,
    dateofdeath bigint,
    time_of_death integer,
    timeofdeath_unit character varying(50) COLLATE pg_catalog."default",
    date_of_death_to bigint,
    time_of_death_to integer,
    timeofdeath_unit_to character varying(50) COLLATE pg_catalog."default",
    deceased_unidentified smallint,
    deceased_title character varying(64) COLLATE pg_catalog."default",
    deceased_firstname_en character varying(64) COLLATE pg_catalog."default",
    deceased_firstname_ml character varying(64) COLLATE pg_catalog."default",
    deceased_middlename_en character varying(64) COLLATE pg_catalog."default",
    deceased_middlename_ml character varying(64) COLLATE pg_catalog."default",
    deceased_lastname_en character varying(64) COLLATE pg_catalog."default",
    deceased_lastname_ml character varying(64) COLLATE pg_catalog."default",
    deceased_aadhar_number character varying(500) COLLATE pg_catalog."default",
    deceased_gender character varying(64) COLLATE pg_catalog."default",
    age integer,
    age_unit character varying(64) COLLATE pg_catalog."default",
    dateofbirth bigint,
    death_place character varying(64) COLLATE pg_catalog."default",
    death_place_inst_type character varying(64) COLLATE pg_catalog."default",
    death_place_inst_id character varying(64) COLLATE pg_catalog."default",
    death_place_officer_name character varying(200) COLLATE pg_catalog."default",
    death_place_other_ml character varying(200) COLLATE pg_catalog."default",
    death_place_other_en character varying(200) COLLATE pg_catalog."default",
    informant_title character varying(64) COLLATE pg_catalog."default",
    informant_name_en character varying(64) COLLATE pg_catalog."default",
    informant_name_ml character varying(64) COLLATE pg_catalog."default",
    informant_aadhar_submitted boolean,
    informant_aadhar_no character varying(500) COLLATE pg_catalog."default",
    informant_mobile_no character varying(64) COLLATE pg_catalog."default",
    general_remarks character varying(500) COLLATE pg_catalog."default",
    status character varying(64) COLLATE pg_catalog."default",
    submitted_on bigint,
    created_by character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    burial_district character varying(64) COLLATE pg_catalog."default",
    burial_lbtype character varying(64) COLLATE pg_catalog."default",
    burial_lbname character varying(64) COLLATE pg_catalog."default",
    registration_no character varying(64) COLLATE pg_catalog."default",
    ip_no character varying(64) COLLATE pg_catalog."default",
    op_no character varying(64) COLLATE pg_catalog."default",
    male_dependent_type character varying(64) COLLATE pg_catalog."default",
    male_dependent_title character varying(64) COLLATE pg_catalog."default",
    male_dependent_name_en character varying(64) COLLATE pg_catalog."default",
    male_dependent_name_ml character varying(64) COLLATE pg_catalog."default",
    male_dependent_aadharno character varying(500) COLLATE pg_catalog."default",
    male_dependent_mobileno character varying(64) COLLATE pg_catalog."default",
    male_dependent_mailid character varying(64) COLLATE pg_catalog."default",
    female_dependent_type character varying(64) COLLATE pg_catalog."default",
    female_dependent_title character varying(64) COLLATE pg_catalog."default",
    female_dependent_name_en character varying(64) COLLATE pg_catalog."default",
    female_dependent_name_ml character varying(64) COLLATE pg_catalog."default",
    female_dependent_aadharno character varying(500) COLLATE pg_catalog."default",
    female_dependent_mobileno character varying(64) COLLATE pg_catalog."default",
    female_dependent_mailid character varying(64) COLLATE pg_catalog."default",
    isvehicle smallint,
    vehicle_hospital_ml character varying(200) COLLATE pg_catalog."default",
    vehicle_hospital_en character varying(200) COLLATE pg_catalog."default",
    vehicle_fromplace_ml character varying(200) COLLATE pg_catalog."default",
    vehicle_fromplace_en character varying(200) COLLATE pg_catalog."default",
    vehicle_toplace_ml character varying(200) COLLATE pg_catalog."default",
    vehicle_toplace_en character varying(200) COLLATE pg_catalog."default",
    vehicle_number character varying(64) COLLATE pg_catalog."default",
    death_place_ward_id character varying(64) COLLATE pg_catalog."default",
    informant_age character varying(64) COLLATE pg_catalog."default",
    vehicle_driver_licenceno character varying(64) COLLATE pg_catalog."default",
    death_signed_officer_designation character varying(64) COLLATE pg_catalog."default",
    death_place_officer_mobile character varying(64) COLLATE pg_catalog."default",
    death_place_officer_aadhaar character varying(500) COLLATE pg_catalog."default",
    application_no character varying(64) COLLATE pg_catalog."default",
    file_no character varying(64) COLLATE pg_catalog."default",
    ack_no character varying(64) COLLATE pg_catalog."default",
    workflowcode character varying(64) COLLATE pg_catalog."default",
    businessservice character varying(64) COLLATE pg_catalog."default",
    action character varying(64) COLLATE pg_catalog."default",
    comment character varying(64) COLLATE pg_catalog."default",
    assignee character varying(64) COLLATE pg_catalog."default",
    registration_date bigint,
    registration_no_id bigint,
    appl_type character varying(64) COLLATE pg_catalog."default",
    deceased_idproofno character varying(500) COLLATE pg_catalog."default",
    deceased_idprooftype character varying(64) COLLATE pg_catalog."default",
    kiosk_id bigint,
    burial_state character varying(64) COLLATE pg_catalog."default",
    vehicle_first_halt character varying(200) COLLATE pg_catalog."default",
    male_dependent_unavailable boolean,
    female_dependent_unavailable boolean,
    spouse_name_en character varying(64) COLLATE pg_catalog."default",
    spouse_name_ml character varying(64) COLLATE pg_catalog."default",
    spouse_unavailable boolean,
    spouse_type character varying(64) COLLATE pg_catalog."default",
    spouse_emailid character varying(64) COLLATE pg_catalog."default",
    spouse_aadhaar character varying(500) COLLATE pg_catalog."default",
    spouse_mobileno character varying(64) COLLATE pg_catalog."default",
    funcion_uid character varying(64) COLLATE pg_catalog."default",
    ack_no_id bigint,
    application_date bigint,
    other_vehicle_type character varying(64) COLLATE pg_catalog."default",
    deceased_aadhar_unavailable boolean,
    vehicle_first_halt_ml character varying(200) COLLATE pg_catalog."default",
    death_place_locality_en character varying(200) COLLATE pg_catalog."default",
    death_place_locality_ml character varying(200) COLLATE pg_catalog."default",
    death_place_street_en character varying(200) COLLATE pg_catalog."default",
    death_place_street_ml character varying(200) COLLATE pg_catalog."default",
    death_place_country character varying(200) COLLATE pg_catalog."default",
    death_place_state character varying(200) COLLATE pg_catalog."default",
    death_place_district character varying(200) COLLATE pg_catalog."default",
    death_place_city character varying(200) COLLATE pg_catalog."default",
    death_place_remarks_en character varying(500) COLLATE pg_catalog."default",
    death_place_remarks_ml character varying(500) COLLATE pg_catalog."default",
    place_of_burial_en character varying(200) COLLATE pg_catalog."default",
    place_of_burial_ml character varying(200) COLLATE pg_catalog."default",
    death_home_locality_en character varying(200) COLLATE pg_catalog."default",
    death_home_locality_ml character varying(200) COLLATE pg_catalog."default",
    death_home_street_en character varying(200) COLLATE pg_catalog."default",
    death_home_street_ml character varying(200) COLLATE pg_catalog."default",
    death_home_housename_en character varying(500) COLLATE pg_catalog."default",
    death_home_housename_ml character varying(500) COLLATE pg_catalog."default",
    death_home_postoffice_id character varying(200) COLLATE pg_catalog."default",
    death_home_postofficename_en character varying(200) COLLATE pg_catalog."default",
    death_home_postofficename_ml character varying(200) COLLATE pg_catalog."default",
    death_home_pincode character varying(50) COLLATE pg_catalog."default",
    death_home_ward character varying(200) COLLATE pg_catalog."default",
    death_home_taluk_id character varying(200) COLLATE pg_catalog."default",
    death_home_taluk_en character varying(500) COLLATE pg_catalog."default",
    death_home_taluk_ml character varying(500) COLLATE pg_catalog."default",
    family_mobile_no bigint,
    family_email character varying(200) COLLATE pg_catalog."default",
    initiator_name character varying(200) COLLATE pg_catalog."default",
    initiator_aadhar_submitted boolean,
    initiator_aadhar_no character varying(500) COLLATE pg_catalog."default",
    initiator_mobile_no bigint,
    initiator_relation character varying(64) COLLATE pg_catalog."default",
    informant_address character varying(500) COLLATE pg_catalog."default",
    initiator_address character varying(500) COLLATE pg_catalog."default",
    is_declaration_initiator boolean,
    is_declaration_informant boolean,
    CONSTRAINT eg_death_dtls_pkey1 PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_dtls
    OWNER to postgres;

--2

-- Table: public.eg_death_dtls_log

-- DROP TABLE IF EXISTS public.eg_death_dtls_log;

CREATE TABLE IF NOT EXISTS public.eg_death_dtls_log
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    registrationunit character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    correct_death_date_known smallint,
    dateofdeath bigint,
    time_of_death integer,
    timeofdeath_unit character varying(50) COLLATE pg_catalog."default",
    date_of_death_to bigint,
    time_of_death_to integer,
    timeofdeath_unit_to character varying(50) COLLATE pg_catalog."default",
    deceased_unidentifiedack_no smallint,
    deceased_title character varying(64) COLLATE pg_catalog."default",
    deceased_firstname_en character varying(64) COLLATE pg_catalog."default",
    deceased_firstname_ml character varying(64) COLLATE pg_catalog."default",
    deceased_middlename_en character varying(64) COLLATE pg_catalog."default",
    deceased_middlename_ml character varying(64) COLLATE pg_catalog."default",
    deceased_lastname_en character varying(64) COLLATE pg_catalog."default",
    deceased_lastname_ml character varying(64) COLLATE pg_catalog."default",
    deceased_aadhar_number character varying(500) COLLATE pg_catalog."default",
    deceased_gender character varying(64) COLLATE pg_catalog."default",
    age integer,
    age_unit character varying(64) COLLATE pg_catalog."default",
    dateofbirth bigint,
    death_place character varying(64) COLLATE pg_catalog."default",
    death_place_inst_type character varying(64) COLLATE pg_catalog."default",
    death_place_inst_id character varying(64) COLLATE pg_catalog."default",
    death_place_officer_name character varying(200) COLLATE pg_catalog."default",
    death_place_other_ml character varying(200) COLLATE pg_catalog."default",
    death_place_other_en character varying(200) COLLATE pg_catalog."default",
    informant_title character varying(64) COLLATE pg_catalog."default",
    informant_name_en character varying(64) COLLATE pg_catalog."default",
    informant_name_ml character varying(64) COLLATE pg_catalog."default",
    informant_aadhar_submitted boolean,
    informant_aadhar_no character varying(500) COLLATE pg_catalog."default",
    informant_mobile_no character varying(64) COLLATE pg_catalog."default",
    general_remarks character varying(500) COLLATE pg_catalog."default",
    status character varying(64) COLLATE pg_catalog."default",
    submitted_on bigint,
    created_by character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    burial_district character varying(64) COLLATE pg_catalog."default",
    burial_lbtype character varying(64) COLLATE pg_catalog."default",
    burial_lbname character varying(64) COLLATE pg_catalog."default",
    registration_no character varying(64) COLLATE pg_catalog."default",
    ip_no character varying(64) COLLATE pg_catalog."default",
    op_no character varying(64) COLLATE pg_catalog."default",
    male_dependent_type character varying(64) COLLATE pg_catalog."default",
    male_dependent_title character varying(64) COLLATE pg_catalog."default",
    male_dependent_name_en character varying(64) COLLATE pg_catalog."default",
    male_dependent_name_ml character varying(64) COLLATE pg_catalog."default",
    male_dependent_aadharno character varying(500) COLLATE pg_catalog."default",
    male_dependent_mobileno character varying(64) COLLATE pg_catalog."default",
    male_dependent_mailid character varying(64) COLLATE pg_catalog."default",
    female_dependent_type character varying(64) COLLATE pg_catalog."default",
    female_dependent_title character varying(64) COLLATE pg_catalog."default",
    female_dependent_name_en character varying(64) COLLATE pg_catalog."default",
    female_dependent_name_ml character varying(64) COLLATE pg_catalog."default",
    female_dependent_aadharno character varying(500) COLLATE pg_catalog."default",
    female_dependent_mobileno character varying(64) COLLATE pg_catalog."default",
    female_dependent_mailid character varying(64) COLLATE pg_catalog."default",
    isvehicle smallint,
    vehicle_hospital_ml character varying(200) COLLATE pg_catalog."default",
    vehicle_hospital_en character varying(200) COLLATE pg_catalog."default",
    vehicle_fromplace_ml character varying(200) COLLATE pg_catalog."default",
    vehicle_fromplace_en character varying(200) COLLATE pg_catalog."default",
    vehicle_toplace_ml character varying(200) COLLATE pg_catalog."default",
    vehicle_toplace_en character varying(200) COLLATE pg_catalog."default",
    vehicle_number character varying(64) COLLATE pg_catalog."default",
    death_place_ward_id character varying(64) COLLATE pg_catalog."default",
    informant_age character varying(64) COLLATE pg_catalog."default",
    vehicle_driver_licenceno character varying(64) COLLATE pg_catalog."default",
    death_signed_officer_designation character varying(64) COLLATE pg_catalog."default",
    death_place_officer_mobile character varying(64) COLLATE pg_catalog."default",
    death_place_officer_aadhaar character varying(500) COLLATE pg_catalog."default",
    application_no character varying(64) COLLATE pg_catalog."default",
    file_no character varying(64) COLLATE pg_catalog."default",
    ack_no character varying(64) COLLATE pg_catalog."default",
    workflowcode character varying(64) COLLATE pg_catalog."default",
    businessservice character varying(64) COLLATE pg_catalog."default",
    action character varying(64) COLLATE pg_catalog."default",
    comment character varying(64) COLLATE pg_catalog."default",
    assignee character varying(64) COLLATE pg_catalog."default",
    registration_date bigint,
    registration_no_id bigint,
    appl_type character varying(64) COLLATE pg_catalog."default",
    deceased_idproofno character varying(500) COLLATE pg_catalog."default",
    deceased_idprooftype character varying(64) COLLATE pg_catalog."default",
    kiosk_id bigint,
    burial_state character varying(64) COLLATE pg_catalog."default",
    vehicle_first_halt character varying(200) COLLATE pg_catalog."default",
    male_dependent_unavailable boolean,
    female_dependent_unavailable boolean,
    spouse_name_en character varying(64) COLLATE pg_catalog."default",
    spouse_name_ml character varying(64) COLLATE pg_catalog."default",
    spouse_unavailable boolean,
    spouse_type character varying(64) COLLATE pg_catalog."default",
    spouse_emailid character varying(64) COLLATE pg_catalog."default",
    spouse_aadhaar character varying(500) COLLATE pg_catalog."default",
    spouse_mobileno character varying(64) COLLATE pg_catalog."default",
    funcion_uid character varying(64) COLLATE pg_catalog."default",
    ack_no_id bigint,
    application_date bigint,
    other_vehicle_type character varying(64) COLLATE pg_catalog."default",
    deceased_aadhar_unavailable boolean,
    vehicle_first_halt_ml character varying(200) COLLATE pg_catalog."default",
    death_place_locality_en character varying(200) COLLATE pg_catalog."default",
    death_place_locality_ml character varying(200) COLLATE pg_catalog."default",
    death_place_street_en character varying(200) COLLATE pg_catalog."default",
    death_place_street_ml character varying(200) COLLATE pg_catalog."default",
    death_place_country character varying(200) COLLATE pg_catalog."default",
    death_place_state character varying(200) COLLATE pg_catalog."default",
    death_place_district character varying(200) COLLATE pg_catalog."default",
    death_place_city character varying(200) COLLATE pg_catalog."default",
    death_place_remarks_en character varying(500) COLLATE pg_catalog."default",
    death_place_remarks_ml character varying(500) COLLATE pg_catalog."default",
    place_of_burial_en character varying(200) COLLATE pg_catalog."default",
    place_of_burial_ml character varying(200) COLLATE pg_catalog."default",
    death_home_locality_en character varying(200) COLLATE pg_catalog."default",
    death_home_locality_ml character varying(200) COLLATE pg_catalog."default",
    death_home_street_en character varying(200) COLLATE pg_catalog."default",
    death_home_street_ml character varying(200) COLLATE pg_catalog."default",
    death_home_housename_en character varying(500) COLLATE pg_catalog."default",
    death_home_housename_ml character varying(500) COLLATE pg_catalog."default",
    death_home_postoffice_id character varying(200) COLLATE pg_catalog."default",
    death_home_postofficename_en character varying(200) COLLATE pg_catalog."default",
    death_home_postofficename_ml character varying(200) COLLATE pg_catalog."default",
    death_home_pincode character varying(50) COLLATE pg_catalog."default",
    death_home_ward character varying(200) COLLATE pg_catalog."default",
    death_home_taluk_id character varying(200) COLLATE pg_catalog."default",
    death_home_taluk_en character varying(500) COLLATE pg_catalog."default",
    death_home_taluk_ml character varying(500) COLLATE pg_catalog."default",
    family_mobile_no bigint,
    family_email character varying(200) COLLATE pg_catalog."default",
    initiator_name character varying(200) COLLATE pg_catalog."default",
    initiator_aadhar_submitted boolean,
    initiator_aadhar_no character varying(500) COLLATE pg_catalog."default",
    initiator_mobile_no bigint,
    initiator_relation character varying(64) COLLATE pg_catalog."default",
    informant_address character varying(500) COLLATE pg_catalog."default",
    initiator_address character varying(500) COLLATE pg_catalog."default",
    is_declaration_initiator boolean,
    is_declaration_informant boolean
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_dtls_log
    OWNER to postgres;
--3
-- Table: public.eg_death_dtls_registry

-- DROP TABLE IF EXISTS public.eg_death_dtls_registry;

CREATE TABLE IF NOT EXISTS public.eg_death_dtls_registry
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    registrationunit character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    death_date_unavailable smallint,
    dateofdeath bigint,
    time_of_death integer,
    timeofdeath_unit character varying(50) COLLATE pg_catalog."default",
    date_of_death_to bigint,
    time_of_death_to integer,
    timeofdeath_unit_to character varying(50) COLLATE pg_catalog."default",
    deceased_unidentified smallint,
    deceased_title character varying(50) COLLATE pg_catalog."default",
    deceased_firstname_en character varying(200) COLLATE pg_catalog."default",
    deceased_firstname_ml character varying(200) COLLATE pg_catalog."default",
    deceased_middlename_en character varying(200) COLLATE pg_catalog."default",
    deceased_middlename_ml character varying(200) COLLATE pg_catalog."default",
    deceased_lastname_en character varying(200) COLLATE pg_catalog."default",
    deceased_lastname_ml character varying(200) COLLATE pg_catalog."default",
    deceased_aadhar_number character varying(500) COLLATE pg_catalog."default",
    deceased_gender character varying(50) COLLATE pg_catalog."default",
    age integer,
    age_unit character varying(64) COLLATE pg_catalog."default",
    dateofbirth bigint,
    death_place character varying(200) COLLATE pg_catalog."default",
    death_place_inst_type character varying(200) COLLATE pg_catalog."default",
    death_place_inst_id character varying(200) COLLATE pg_catalog."default",
    death_place_officer_name character varying(200) COLLATE pg_catalog."default",
    death_place_other_ml character varying(200) COLLATE pg_catalog."default",
    death_place_other_en character varying(200) COLLATE pg_catalog."default",
    informant_title character varying(200) COLLATE pg_catalog."default",
    informant_name_en character varying(200) COLLATE pg_catalog."default",
    informant_name_ml character varying(200) COLLATE pg_catalog."default",
    informant_aadhar_submitted boolean,
    informant_aadhar_no character varying(500) COLLATE pg_catalog."default",
    informant_mobile_no character varying(150) COLLATE pg_catalog."default",
    general_remarks character varying(500) COLLATE pg_catalog."default",
    application_status character varying(150) COLLATE pg_catalog."default",
    submitted_on bigint,
    created_by character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    burial_district character varying(1000) COLLATE pg_catalog."default",
    burial_lbtype character varying(150) COLLATE pg_catalog."default",
    burial_lbname character varying(1000) COLLATE pg_catalog."default",
    registration_no character varying(200) COLLATE pg_catalog."default",
    ip_no character varying(200) COLLATE pg_catalog."default",
    op_no character varying(200) COLLATE pg_catalog."default",
    male_dependent_type character varying(200) COLLATE pg_catalog."default",
    male_dependent_title character varying(200) COLLATE pg_catalog."default",
    male_dependent_name_en character varying(200) COLLATE pg_catalog."default",
    male_dependent_name_ml character varying(200) COLLATE pg_catalog."default",
    male_dependent_aadharno character varying(500) COLLATE pg_catalog."default",
    male_dependent_mobileno character varying(150) COLLATE pg_catalog."default",
    male_dependent_mailid character varying(150) COLLATE pg_catalog."default",
    female_dependent_type character varying(200) COLLATE pg_catalog."default",
    female_dependent_title character varying(200) COLLATE pg_catalog."default",
    female_dependent_name_en character varying(200) COLLATE pg_catalog."default",
    female_dependent_name_ml character varying(200) COLLATE pg_catalog."default",
    female_dependent_aadharno character varying(500) COLLATE pg_catalog."default",
    female_dependent_mobileno character varying(150) COLLATE pg_catalog."default",
    female_dependent_mailid character varying(150) COLLATE pg_catalog."default",
    isvehicle smallint,
    vehicle_hospital_ml character varying(500) COLLATE pg_catalog."default",
    vehicle_hospital_en character varying(500) COLLATE pg_catalog."default",
    vehicle_fromplace_ml character varying(500) COLLATE pg_catalog."default",
    vehicle_fromplace_en character varying(500) COLLATE pg_catalog."default",
    vehicle_toplace_ml character varying(500) COLLATE pg_catalog."default",
    vehicle_toplace_en character varying(500) COLLATE pg_catalog."default",
    vehicle_number character varying(500) COLLATE pg_catalog."default",
    death_place_ward_id character varying(500) COLLATE pg_catalog."default",
    informant_age character varying(500) COLLATE pg_catalog."default",
    vehicle_driver_licenceno character varying(500) COLLATE pg_catalog."default",
    death_signed_officer_designation character varying(500) COLLATE pg_catalog."default",
    death_place_officer_mobile character varying(500) COLLATE pg_catalog."default",
    death_place_officer_aadhaar character varying(500) COLLATE pg_catalog."default",
    application_no character varying(500) COLLATE pg_catalog."default",
    file_no character varying(500) COLLATE pg_catalog."default",
    ack_no character varying(500) COLLATE pg_catalog."default",
    dateofreport bigint,
    registration_date bigint,
    registration_no_id bigint,
    deceased_idproofno character varying(500) COLLATE pg_catalog."default",
    deceased_idprooftype character varying(64) COLLATE pg_catalog."default",
    bad_record smallint,
    record_no character varying(20) COLLATE pg_catalog."default",
    f12_no character varying(20) COLLATE pg_catalog."default",
    f12_issued smallint,
    book_no character varying(20) COLLATE pg_catalog."default",
    is_migrated smallint,
    migration_date bigint,
    kiosk_id bigint,
    burial_state character varying(64) COLLATE pg_catalog."default",
    vehicle_first_halt character varying(200) COLLATE pg_catalog."default",
    male_dependent_unavailable boolean,
    female_dependent_unavailable boolean,
    spouse_name_en character varying(64) COLLATE pg_catalog."default",
    spouse_name_ml character varying(64) COLLATE pg_catalog."default",
    spouse_unavailable boolean,
    spouse_type character varying(64) COLLATE pg_catalog."default",
    spouse_emailid character varying(64) COLLATE pg_catalog."default",
    spouse_aadhaar character varying(500) COLLATE pg_catalog."default",
    spouse_mobileno character varying(64) COLLATE pg_catalog."default",
    funcion_uid character varying(64) COLLATE pg_catalog."default",
    certificate_no_id bigint,
    certificate_no character varying(64) COLLATE pg_catalog."default",
    certificate_date bigint,
    other_vehicle_type character varying(64) COLLATE pg_catalog."default",
    deceased_aadhar_unavailable boolean,
    vehicle_first_halt_ml character varying(200) COLLATE pg_catalog."default",
    death_place_locality_en character varying(200) COLLATE pg_catalog."default",
    death_place_locality_ml character varying(200) COLLATE pg_catalog."default",
    death_place_street_en character varying(200) COLLATE pg_catalog."default",
    death_place_street_ml character varying(200) COLLATE pg_catalog."default",
    death_place_country character varying(200) COLLATE pg_catalog."default",
    death_place_state character varying(200) COLLATE pg_catalog."default",
    death_place_district character varying(200) COLLATE pg_catalog."default",
    death_place_city character varying(200) COLLATE pg_catalog."default",
    death_place_remarks_en character varying(500) COLLATE pg_catalog."default",
    death_place_remarks_ml character varying(500) COLLATE pg_catalog."default",
    place_of_burial_en character varying(200) COLLATE pg_catalog."default",
    place_of_burial_ml character varying(200) COLLATE pg_catalog."default",
    death_home_locality_en character varying(200) COLLATE pg_catalog."default",
    death_home_locality_ml character varying(200) COLLATE pg_catalog."default",
    death_home_street_en character varying(200) COLLATE pg_catalog."default",
    death_home_street_ml character varying(200) COLLATE pg_catalog."default",
    death_home_housename_en character varying(500) COLLATE pg_catalog."default",
    death_home_housename_ml character varying(500) COLLATE pg_catalog."default",
    death_home_postoffice_id character varying(200) COLLATE pg_catalog."default",
    death_home_postofficename_en character varying(200) COLLATE pg_catalog."default",
    death_home_postofficename_ml character varying(200) COLLATE pg_catalog."default",
    death_home_pincode character varying(50) COLLATE pg_catalog."default",
    death_home_ward character varying(200) COLLATE pg_catalog."default",
    death_home_taluk_id character varying(200) COLLATE pg_catalog."default",
    death_home_taluk_en character varying(500) COLLATE pg_catalog."default",
    death_home_taluk_ml character varying(500) COLLATE pg_catalog."default",
    family_mobile_no bigint,
    family_email character varying(200) COLLATE pg_catalog."default",
    informant_address character varying(500) COLLATE pg_catalog."default",
    initiator_address character varying(500) COLLATE pg_catalog."default",
    is_declaration_initiator boolean,
    is_declaration_informant boolean,
    CONSTRAINT eg_death_dtls_registry_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_dtls_registry
    OWNER to postgres;

--4
-- Table: public.eg_death_dtls_registry_log

-- DROP TABLE IF EXISTS public.eg_death_dtls_registry_log;

CREATE TABLE IF NOT EXISTS public.eg_death_dtls_registry_log
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    registrationunit character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    death_date_unavailable smallint,
    dateofdeath bigint,
    time_of_death integer,
    timeofdeath_unit character varying(50) COLLATE pg_catalog."default",
    date_of_death_to bigint,
    time_of_death_to integer,
    timeofdeath_unit_to character varying(50) COLLATE pg_catalog."default",
    deceased_unidentified smallint,
    deceased_title character varying(50) COLLATE pg_catalog."default",
    deceased_firstname_en character varying(200) COLLATE pg_catalog."default",
    deceased_firstname_ml character varying(200) COLLATE pg_catalog."default",
    deceased_middlename_en character varying(200) COLLATE pg_catalog."default",
    deceased_middlename_ml character varying(200) COLLATE pg_catalog."default",
    deceased_lastname_en character varying(200) COLLATE pg_catalog."default",
    deceased_lastname_ml character varying(200) COLLATE pg_catalog."default",
    deceased_aadhar_number character varying(500) COLLATE pg_catalog."default",
    deceased_gender character varying(50) COLLATE pg_catalog."default",
    age integer,
    age_unit character varying(64) COLLATE pg_catalog."default",
    dateofbirth bigint,
    death_place character varying(200) COLLATE pg_catalog."default",
    death_place_inst_type character varying(200) COLLATE pg_catalog."default",
    death_place_inst_id character varying(200) COLLATE pg_catalog."default",
    death_place_officer_name character varying(200) COLLATE pg_catalog."default",
    death_place_other_ml character varying(200) COLLATE pg_catalog."default",
    death_place_other_en character varying(200) COLLATE pg_catalog."default",
    informant_title character varying(200) COLLATE pg_catalog."default",
    informant_name_en character varying(200) COLLATE pg_catalog."default",
    informant_name_ml character varying(200) COLLATE pg_catalog."default",
    informant_aadhar_submitted boolean,
    informant_aadhar_no character varying(500) COLLATE pg_catalog."default",
    informant_mobile_no character varying(150) COLLATE pg_catalog."default",
    general_remarks character varying(500) COLLATE pg_catalog."default",
    application_status character varying(150) COLLATE pg_catalog."default",
    submitted_on bigint,
    created_by character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    burial_district character varying(1000) COLLATE pg_catalog."default",
    burial_lbtype character varying(150) COLLATE pg_catalog."default",
    burial_lbname character varying(1000) COLLATE pg_catalog."default",
    registration_no character varying(200) COLLATE pg_catalog."default",
    ip_no character varying(200) COLLATE pg_catalog."default",
    op_no character varying(200) COLLATE pg_catalog."default",
    male_dependent_type character varying(200) COLLATE pg_catalog."default",
    male_dependent_title character varying(200) COLLATE pg_catalog."default",
    male_dependent_name_en character varying(200) COLLATE pg_catalog."default",
    male_dependent_name_ml character varying(200) COLLATE pg_catalog."default",
    male_dependent_aadharno character varying(500) COLLATE pg_catalog."default",
    male_dependent_mobileno character varying(150) COLLATE pg_catalog."default",
    male_dependent_mailid character varying(150) COLLATE pg_catalog."default",
    female_dependent_type character varying(200) COLLATE pg_catalog."default",
    female_dependent_title character varying(200) COLLATE pg_catalog."default",
    female_dependent_name_en character varying(200) COLLATE pg_catalog."default",
    female_dependent_name_ml character varying(200) COLLATE pg_catalog."default",
    female_dependent_aadharno character varying(500) COLLATE pg_catalog."default",
    female_dependent_mobileno character varying(150) COLLATE pg_catalog."default",
    female_dependent_mailid character varying(150) COLLATE pg_catalog."default",
    isvehicle smallint,
    vehicle_hospital_ml character varying(500) COLLATE pg_catalog."default",
    vehicle_hospital_en character varying(500) COLLATE pg_catalog."default",
    vehicle_fromplace_ml character varying(500) COLLATE pg_catalog."default",
    vehicle_fromplace_en character varying(500) COLLATE pg_catalog."default",
    vehicle_toplace_ml character varying(500) COLLATE pg_catalog."default",
    vehicle_toplace_en character varying(500) COLLATE pg_catalog."default",
    vehicle_number character varying(500) COLLATE pg_catalog."default",
    death_place_ward_id character varying(500) COLLATE pg_catalog."default",
    informant_age character varying(500) COLLATE pg_catalog."default",
    vehicle_driver_licenceno character varying(500) COLLATE pg_catalog."default",
    death_signed_officer_designation character varying(500) COLLATE pg_catalog."default",
    death_place_officer_mobile character varying(500) COLLATE pg_catalog."default",
    death_place_officer_aadhaar character varying(500) COLLATE pg_catalog."default",
    application_no character varying(500) COLLATE pg_catalog."default",
    file_no character varying(500) COLLATE pg_catalog."default",
    ack_no character varying(500) COLLATE pg_catalog."default",
    dateofreport bigint,
    registration_date bigint,
    registration_no_id bigint,
    deceased_idproofno character varying(500) COLLATE pg_catalog."default",
    deceased_idprooftype character varying(64) COLLATE pg_catalog."default",
    bad_record smallint,
    record_no character varying(20) COLLATE pg_catalog."default",
    f12_no character varying(20) COLLATE pg_catalog."default",
    f12_issued smallint,
    book_no character varying(20) COLLATE pg_catalog."default",
    is_migrated smallint,
    migration_date bigint,
    kiosk_id bigint,
    burial_state character varying(64) COLLATE pg_catalog."default",
    vehicle_first_halt character varying(200) COLLATE pg_catalog."default",
    male_dependent_unavailable boolean,
    female_dependent_unavailable boolean,
    spouse_name_en character varying(64) COLLATE pg_catalog."default",
    spouse_name_ml character varying(64) COLLATE pg_catalog."default",
    spouse_unavailable boolean,
    spouse_type character varying(64) COLLATE pg_catalog."default",
    spouse_emailid character varying(64) COLLATE pg_catalog."default",
    spouse_aadhaar character varying(500) COLLATE pg_catalog."default",
    spouse_mobileno character varying(64) COLLATE pg_catalog."default",
    funcion_uid character varying(64) COLLATE pg_catalog."default",
    certificate_no_id bigint,
    certificate_no character varying(64) COLLATE pg_catalog."default",
    certificate_date bigint,
    other_vehicle_type character varying(64) COLLATE pg_catalog."default",
    deceased_aadhar_unavailable boolean,
    vehicle_first_halt_ml character varying(200) COLLATE pg_catalog."default",
    death_place_locality_en character varying(200) COLLATE pg_catalog."default",
    death_place_locality_ml character varying(200) COLLATE pg_catalog."default",
    death_place_street_en character varying(200) COLLATE pg_catalog."default",
    death_place_street_ml character varying(200) COLLATE pg_catalog."default",
    death_place_country character varying(200) COLLATE pg_catalog."default",
    death_place_state character varying(200) COLLATE pg_catalog."default",
    death_place_district character varying(200) COLLATE pg_catalog."default",
    death_place_city character varying(200) COLLATE pg_catalog."default",
    death_place_remarks_en character varying(500) COLLATE pg_catalog."default",
    death_place_remarks_ml character varying(500) COLLATE pg_catalog."default",
    place_of_burial_en character varying(200) COLLATE pg_catalog."default",
    place_of_burial_ml character varying(200) COLLATE pg_catalog."default",
    death_home_locality_en character varying(200) COLLATE pg_catalog."default",
    death_home_locality_ml character varying(200) COLLATE pg_catalog."default",
    death_home_street_en character varying(200) COLLATE pg_catalog."default",
    death_home_street_ml character varying(200) COLLATE pg_catalog."default",
    death_home_housename_en character varying(500) COLLATE pg_catalog."default",
    death_home_housename_ml character varying(500) COLLATE pg_catalog."default",
    death_home_postoffice_id character varying(200) COLLATE pg_catalog."default",
    death_home_postofficename_en character varying(200) COLLATE pg_catalog."default",
    death_home_postofficename_ml character varying(200) COLLATE pg_catalog."default",
    death_home_pincode character varying(50) COLLATE pg_catalog."default",
    death_home_ward character varying(200) COLLATE pg_catalog."default",
    death_home_taluk_id character varying(200) COLLATE pg_catalog."default",
    death_home_taluk_en character varying(500) COLLATE pg_catalog."default",
    death_home_taluk_ml character varying(500) COLLATE pg_catalog."default",
    family_mobile_no bigint,
    family_email character varying(200) COLLATE pg_catalog."default",
    informant_address character varying(500) COLLATE pg_catalog."default",
    initiator_address character varying(500) COLLATE pg_catalog."default",
    is_declaration_initiator boolean,
    is_declaration_informant boolean
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_dtls_registry_log
    OWNER to postgres;
--5
-- Table: public.eg_death_statistical_dtls

-- DROP TABLE IF EXISTS public.eg_death_statistical_dtls;

CREATE TABLE IF NOT EXISTS public.eg_death_statistical_dtls
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    death_dtl_id character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    residencelocalbody character varying(75) COLLATE pg_catalog."default",
    residence_place_type character varying(200) COLLATE pg_catalog."default",
    residencedistrict character varying(250) COLLATE pg_catalog."default",
    residencestate character varying(100) COLLATE pg_catalog."default",
    religion character varying(200) COLLATE pg_catalog."default",
    religion_other character varying(100) COLLATE pg_catalog."default",
    occupation character varying(100) COLLATE pg_catalog."default",
    occupation_other character varying(500) COLLATE pg_catalog."default",
    medical_attention_type character varying(500) COLLATE pg_catalog."default",
    death_medically_certified character varying(50) COLLATE pg_catalog."default",
    death_cause_main character varying(200) COLLATE pg_catalog."default",
    death_cause_sub character varying(200) COLLATE pg_catalog."default",
    death_cause_other character varying(200) COLLATE pg_catalog."default",
    death_during_delivery character varying(200) COLLATE pg_catalog."default",
    smoking_num_years integer,
    tobacco_num_years integer,
    arecanut_num_years integer,
    alcohol_num_years integer,
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    nationality character varying(200) COLLATE pg_catalog."default",
    occupation_sub character varying(64) COLLATE pg_catalog."default",
    occupation_minor character varying(64) COLLATE pg_catalog."default",
    education_main character varying(64) COLLATE pg_catalog."default",
    education_sub character varying(64) COLLATE pg_catalog."default",
    residencelbtype character varying(64) COLLATE pg_catalog."default",
    smoking_type character varying(64) COLLATE pg_catalog."default",
    tobacco_type character varying(64) COLLATE pg_catalog."default",
    arecanut_type integer,
    alcohol_type character varying(64) COLLATE pg_catalog."default",
    autopsy_performed character varying(50) COLLATE pg_catalog."default",
    autopsy_completed character varying(50) COLLATE pg_catalog."default",
    manner_of_death character varying(200) COLLATE pg_catalog."default",
    death_cause_main_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_main_interval integer,
    death_cause_main_timeunit character varying(200) COLLATE pg_catalog."default",
    death_cause_sub_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_sub_interval integer,
    death_cause_sub_timeunit character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2 character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2_interval integer,
    death_cause_sub2_timeunit character varying(200) COLLATE pg_catalog."default",
    deceased_pregnant character varying(200) COLLATE pg_catalog."default",
    is_delivery character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT eg_death_statistical_dtls_pkey PRIMARY KEY (id),
    CONSTRAINT fk_eg_death_dtls FOREIGN KEY (death_dtl_id)
        REFERENCES public.eg_death_dtls (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_statistical_dtls
    OWNER to postgres;
--6
-- Table: public.eg_death_statistical_dtls_log

-- DROP TABLE IF EXISTS public.eg_death_statistical_dtls_log;

CREATE TABLE IF NOT EXISTS public.eg_death_statistical_dtls_log
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    death_dtl_id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    tenantid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    residencelocalbody character varying(75) COLLATE pg_catalog."default",
    residence_place_type character varying(200) COLLATE pg_catalog."default",
    residencedistrict character varying(250) COLLATE pg_catalog."default",
    residencestate character varying(100) COLLATE pg_catalog."default",
    religion character varying(200) COLLATE pg_catalog."default",
    religion_other character varying(100) COLLATE pg_catalog."default",
    occupation character varying(100) COLLATE pg_catalog."default",
    occupation_other character varying(500) COLLATE pg_catalog."default",
    medical_attention_type character varying(500) COLLATE pg_catalog."default",
    death_medically_certified character varying(50) COLLATE pg_catalog."default",
    death_cause_main character varying(200) COLLATE pg_catalog."default",
    death_cause_sub character varying(200) COLLATE pg_catalog."default",
    death_cause_other character varying(200) COLLATE pg_catalog."default",
    death_during_delivery character varying(200) COLLATE pg_catalog."default",
    smoking_num_years integer,
    tobacco_num_years integer,
    arecanut_num_years integer,
    alcohol_num_years integer,
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    nationality character varying(200) COLLATE pg_catalog."default",
    occupation_sub character varying(64) COLLATE pg_catalog."default",
    occupation_minor character varying(64) COLLATE pg_catalog."default",
    education_main character varying(64) COLLATE pg_catalog."default",
    education_sub character varying(64) COLLATE pg_catalog."default",
    residencelbtype character varying(64) COLLATE pg_catalog."default",
    smoking_type character varying(64) COLLATE pg_catalog."default",
    tobacco_type character varying(64) COLLATE pg_catalog."default",
    arecanut_type integer,
    alcohol_type character varying(64) COLLATE pg_catalog."default",
    autopsy_performed character varying(50) COLLATE pg_catalog."default",
    autopsy_completed character varying(50) COLLATE pg_catalog."default",
    manner_of_death character varying(200) COLLATE pg_catalog."default",
    death_cause_main_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_main_interval integer,
    death_cause_main_timeunit character varying(200) COLLATE pg_catalog."default",
    death_cause_sub_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_sub_interval integer,
    death_cause_sub_timeunit character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2 character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2_interval integer,
    death_cause_sub2_timeunit character varying(200) COLLATE pg_catalog."default",
    deceased_pregnant character varying(200) COLLATE pg_catalog."default",
    is_delivery character varying(200) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_statistical_dtls_log
    OWNER to postgres;
--7
-- Table: public.eg_death_statistical_registry

-- DROP TABLE IF EXISTS public.eg_death_statistical_registry;

CREATE TABLE IF NOT EXISTS public.eg_death_statistical_registry
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    death_dtl_id character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    residencelocalbody character varying(75) COLLATE pg_catalog."default",
    residence_place_type character varying(200) COLLATE pg_catalog."default",
    residencedistrict character varying(250) COLLATE pg_catalog."default",
    residencestate character varying(100) COLLATE pg_catalog."default",
    religion character varying(200) COLLATE pg_catalog."default",
    religion_other character varying(100) COLLATE pg_catalog."default",
    occupation character varying(100) COLLATE pg_catalog."default",
    occupation_other character varying(500) COLLATE pg_catalog."default",
    medical_attention_type character varying(500) COLLATE pg_catalog."default",
    death_medically_certified character varying(50) COLLATE pg_catalog."default",
    death_cause_main character varying(200) COLLATE pg_catalog."default",
    death_cause_sub character varying(200) COLLATE pg_catalog."default",
    death_cause_other character varying(200) COLLATE pg_catalog."default",
    death_during_delivery character varying(200) COLLATE pg_catalog."default",
    smoking_num_years integer,
    tobacco_num_years integer,
    arecanut_num_years integer,
    alcohol_num_years integer,
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    nationality character varying(200) COLLATE pg_catalog."default",
    occupation_sub character varying(64) COLLATE pg_catalog."default",
    occupation_minor character varying(64) COLLATE pg_catalog."default",
    education_main character varying(64) COLLATE pg_catalog."default",
    education_sub character varying(64) COLLATE pg_catalog."default",
    residencelbtype character varying(64) COLLATE pg_catalog."default",
    smoking_type character varying(64) COLLATE pg_catalog."default",
    tobacco_type character varying(64) COLLATE pg_catalog."default",
    arecanut_type integer,
    alcohol_type character varying(64) COLLATE pg_catalog."default",
    mig_ackno character varying(64) COLLATE pg_catalog."default",
    mig_ack_no character varying(64) COLLATE pg_catalog."default",
    autopsy_performed character varying(50) COLLATE pg_catalog."default",
    autopsy_completed character varying(50) COLLATE pg_catalog."default",
    manner_of_death character varying(200) COLLATE pg_catalog."default",
    death_cause_main_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_main_interval integer,
    death_cause_main_timeunit character varying(200) COLLATE pg_catalog."default",
    death_cause_sub_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_sub_interval integer,
    death_cause_sub_timeunit character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2 character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2_interval integer,
    death_cause_sub2_timeunit character varying(200) COLLATE pg_catalog."default",
    deceased_pregnant character varying(200) COLLATE pg_catalog."default",
    is_delivery character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT eg_death_statistical_registry_pkey PRIMARY KEY (id),
    CONSTRAINT fk_eg_death_dtls_registry FOREIGN KEY (death_dtl_id)
        REFERENCES public.eg_death_dtls_registry (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_statistical_registry
    OWNER to postgres;
--8
-- Table: public.eg_death_statistical_registry_log

-- DROP TABLE IF EXISTS public.eg_death_statistical_registry_log;

CREATE TABLE IF NOT EXISTS public.eg_death_statistical_registry_log
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    death_dtl_id character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    residencelocalbody character varying(100) COLLATE pg_catalog."default",
    residence_place_type character varying(200) COLLATE pg_catalog."default",
    residencedistrict character varying(250) COLLATE pg_catalog."default",
    residencestate character varying(200) COLLATE pg_catalog."default",
    religion character varying(200) COLLATE pg_catalog."default",
    religion_other character varying(200) COLLATE pg_catalog."default",
    occupation character varying(200) COLLATE pg_catalog."default",
    occupation_other character varying(200) COLLATE pg_catalog."default",
    medical_attention_type character varying(500) COLLATE pg_catalog."default",
    death_medically_certified character varying(50) COLLATE pg_catalog."default",
    death_cause_main character varying(200) COLLATE pg_catalog."default",
    death_cause_sub character varying(200) COLLATE pg_catalog."default",
    death_cause_other character varying(200) COLLATE pg_catalog."default",
    death_during_delivery character varying(200) COLLATE pg_catalog."default",
    smoking_num_years integer,
    tobacco_num_years integer,
    arecanut_num_years integer,
    alcohol_num_years integer,
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    nationality character varying(200) COLLATE pg_catalog."default",
    occupation_sub character varying(64) COLLATE pg_catalog."default",
    occupation_minor character varying(64) COLLATE pg_catalog."default",
    education_main character varying(64) COLLATE pg_catalog."default",
    education_sub character varying(64) COLLATE pg_catalog."default",
    residencelbtype character varying(64) COLLATE pg_catalog."default",
    smoking_type character varying(64) COLLATE pg_catalog."default",
    tobacco_type character varying(64) COLLATE pg_catalog."default",
    arecanut_type integer,
    alcohol_type character varying(64) COLLATE pg_catalog."default",
    mig_ackno character varying(64) COLLATE pg_catalog."default",
    mig_ack_no character varying(64) COLLATE pg_catalog."default",
    autopsy_performed character varying(50) COLLATE pg_catalog."default",
    autopsy_completed character varying(50) COLLATE pg_catalog."default",
    manner_of_death character varying(200) COLLATE pg_catalog."default",
    death_cause_main_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_main_interval integer,
    death_cause_main_timeunit character varying(200) COLLATE pg_catalog."default",
    death_cause_sub_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_sub_interval integer,
    death_cause_sub_timeunit character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2 character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2_custom character varying(200) COLLATE pg_catalog."default",
    death_cause_sub2_interval integer,
    death_cause_sub2_timeunit character varying(200) COLLATE pg_catalog."default",
    deceased_pregnant character varying(200) COLLATE pg_catalog."default",
    is_delivery character varying(200) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_statistical_registry_log
    OWNER to postgres;
--9
-- Table: public.eg_death_address_dtls

-- DROP TABLE IF EXISTS public.eg_death_address_dtls;

CREATE TABLE IF NOT EXISTS public.eg_death_address_dtls
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    death_dtl_id character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default",
    addr_typeid character varying(50) COLLATE pg_catalog."default",
    house_no character varying(100) COLLATE pg_catalog."default",
    residence_assc_no character varying(100) COLLATE pg_catalog."default",
    streetname_en character varying(200) COLLATE pg_catalog."default",
    streetname_ml character varying(200) COLLATE pg_catalog."default",
    locality_en character varying(200) COLLATE pg_catalog."default",
    locality_ml character varying(200) COLLATE pg_catalog."default",
    city_en character varying(200) COLLATE pg_catalog."default",
    city_ml character varying(200) COLLATE pg_catalog."default",
    ward_id character varying(100) COLLATE pg_catalog."default",
    taluk_id character varying(100) COLLATE pg_catalog."default",
    village_id character varying(200) COLLATE pg_catalog."default",
    postoffice_id character varying(200) COLLATE pg_catalog."default",
    pincode character varying(50) COLLATE pg_catalog."default",
    district_id character varying(100) COLLATE pg_catalog."default",
    state_id character varying(100) COLLATE pg_catalog."default",
    country_id character varying(100) COLLATE pg_catalog."default",
    taluk_name_en character varying(200) COLLATE pg_catalog."default",
    taluk_name_ml character varying(200) COLLATE pg_catalog."default",
    village_name_en character varying(200) COLLATE pg_catalog."default",
    village_name_ml character varying(200) COLLATE pg_catalog."default",
    postoffice_name_en character varying(200) COLLATE pg_catalog."default",
    postoffice_name_ml character varying(200) COLLATE pg_catalog."default",
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    location_type character varying(150) COLLATE pg_catalog."default",
    housename_ml character varying(500) COLLATE pg_catalog."default",
    housename_en character varying(500) COLLATE pg_catalog."default",
    lbtype character varying(200) COLLATE pg_catalog."default",
    postal_code character varying(200) COLLATE pg_catalog."default",
    province_name_en character varying(200) COLLATE pg_catalog."default",
    province_name_ml character varying(200) COLLATE pg_catalog."default",
    city_town_village character varying(200) COLLATE pg_catalog."default",
    addr_lb_name character varying(200) COLLATE pg_catalog."default",
    addr_sameas_present boolean,
    CONSTRAINT eg_death_address_dtls_pkey PRIMARY KEY (id),
    CONSTRAINT fk_eg_death_dtls FOREIGN KEY (death_dtl_id)
        REFERENCES public.eg_death_dtls (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_address_dtls
    OWNER to postgres;
--10
-- Table: public.eg_death_address_dtls_log

-- DROP TABLE IF EXISTS public.eg_death_address_dtls_log;

CREATE TABLE IF NOT EXISTS public.eg_death_address_dtls_log
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    death_dtl_id character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default",
    addr_typeid character varying(50) COLLATE pg_catalog."default",
    house_no character varying(100) COLLATE pg_catalog."default",
    residence_assc_no character varying(100) COLLATE pg_catalog."default",
    streetname_en character varying(200) COLLATE pg_catalog."default",
    streetname_ml character varying(200) COLLATE pg_catalog."default",
    locality_en character varying(200) COLLATE pg_catalog."default",
    locality_ml character varying(200) COLLATE pg_catalog."default",
    city_en character varying(200) COLLATE pg_catalog."default",
    city_ml character varying(200) COLLATE pg_catalog."default",
    ward_id character varying(100) COLLATE pg_catalog."default",
    taluk_id character varying(100) COLLATE pg_catalog."default",
    village_id character varying(200) COLLATE pg_catalog."default",
    postoffice_id character varying(200) COLLATE pg_catalog."default",
    pincode character varying(50) COLLATE pg_catalog."default",
    district_id character varying(100) COLLATE pg_catalog."default",
    state_id character varying(100) COLLATE pg_catalog."default",
    country_id character varying(100) COLLATE pg_catalog."default",
    taluk_name_en character varying(200) COLLATE pg_catalog."default",
    taluk_name_ml character varying(200) COLLATE pg_catalog."default",
    village_name_en character varying(200) COLLATE pg_catalog."default",
    village_name_ml character varying(200) COLLATE pg_catalog."default",
    postoffice_name_en character varying(200) COLLATE pg_catalog."default",
    postoffice_name_ml character varying(200) COLLATE pg_catalog."default",
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    location_type character varying(64) COLLATE pg_catalog."default",
    housename_ml character varying(500) COLLATE pg_catalog."default",
    housename_en character varying(500) COLLATE pg_catalog."default",
    lbtype character varying(200) COLLATE pg_catalog."default",
    postal_code character varying(200) COLLATE pg_catalog."default",
    province_name_en character varying(200) COLLATE pg_catalog."default",
    province_name_ml character varying(200) COLLATE pg_catalog."default",
    city_town_village character varying(200) COLLATE pg_catalog."default",
    addr_lb_name character varying(200) COLLATE pg_catalog."default",
    addr_sameas_present boolean
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_address_dtls_log
    OWNER to postgres;
--11
-- Table: public.eg_death_address_registry

-- DROP TABLE IF EXISTS public.eg_death_address_registry;

CREATE TABLE IF NOT EXISTS public.eg_death_address_registry
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    death_dtl_id character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default",
    addr_typeid character varying(50) COLLATE pg_catalog."default",
    house_no character varying(100) COLLATE pg_catalog."default",
    residence_assc_no character varying(100) COLLATE pg_catalog."default",
    streetname_en character varying(200) COLLATE pg_catalog."default",
    streetname_ml character varying(200) COLLATE pg_catalog."default",
    locality_en character varying(200) COLLATE pg_catalog."default",
    locality_ml character varying(200) COLLATE pg_catalog."default",
    city_en character varying(200) COLLATE pg_catalog."default",
    city_ml character varying(200) COLLATE pg_catalog."default",
    ward_id character varying(100) COLLATE pg_catalog."default",
    taluk_id character varying(100) COLLATE pg_catalog."default",
    village_id character varying(200) COLLATE pg_catalog."default",
    postoffice_id character varying(200) COLLATE pg_catalog."default",
    pincode character varying(50) COLLATE pg_catalog."default",
    district_id character varying(100) COLLATE pg_catalog."default",
    state_id character varying(100) COLLATE pg_catalog."default",
    country_id character varying(100) COLLATE pg_catalog."default",
    taluk_name_en character varying(200) COLLATE pg_catalog."default",
    taluk_name_ml character varying(200) COLLATE pg_catalog."default",
    village_name_en character varying(200) COLLATE pg_catalog."default",
    village_name_ml character varying(200) COLLATE pg_catalog."default",
    postoffice_name_en character varying(200) COLLATE pg_catalog."default",
    postoffice_name_ml character varying(200) COLLATE pg_catalog."default",
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    location_type character varying(150) COLLATE pg_catalog."default",
    housename_ml character varying(500) COLLATE pg_catalog."default",
    housename_en character varying(500) COLLATE pg_catalog."default",
    mig_ackno character varying(64) COLLATE pg_catalog."default",
    mig_ack_no character varying(64) COLLATE pg_catalog."default",
    lbtype character varying(200) COLLATE pg_catalog."default",
    postal_code character varying(200) COLLATE pg_catalog."default",
    province_name_en character varying(200) COLLATE pg_catalog."default",
    province_name_ml character varying(200) COLLATE pg_catalog."default",
    city_town_village character varying(200) COLLATE pg_catalog."default",
    addr_lb_name character varying(200) COLLATE pg_catalog."default",
    addr_sameas_present boolean,
    CONSTRAINT eg_death_address_registry_pkey PRIMARY KEY (id),
    CONSTRAINT fk_eg_death_address_registry FOREIGN KEY (death_dtl_id)
        REFERENCES public.eg_death_dtls_registry (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_address_registry
    OWNER to postgres;
--12
-- Table: public.eg_death_address_registry_log

-- DROP TABLE IF EXISTS public.eg_death_address_registry_log;

CREATE TABLE IF NOT EXISTS public.eg_death_address_registry_log
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    death_dtl_id character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(50) COLLATE pg_catalog."default",
    addr_typeid character varying(50) COLLATE pg_catalog."default",
    house_no character varying(100) COLLATE pg_catalog."default",
    residence_assc_no character varying(100) COLLATE pg_catalog."default",
    streetname_en character varying(200) COLLATE pg_catalog."default",
    streetname_ml character varying(200) COLLATE pg_catalog."default",
    locality_en character varying(200) COLLATE pg_catalog."default",
    locality_ml character varying(200) COLLATE pg_catalog."default",
    city_en character varying(200) COLLATE pg_catalog."default",
    city_ml character varying(200) COLLATE pg_catalog."default",
    ward_id character varying(100) COLLATE pg_catalog."default",
    taluk_id character varying(100) COLLATE pg_catalog."default",
    village_id character varying(200) COLLATE pg_catalog."default",
    postoffice_id character varying(200) COLLATE pg_catalog."default",
    pincode character varying(50) COLLATE pg_catalog."default",
    district_id character varying(100) COLLATE pg_catalog."default",
    state_id character varying(100) COLLATE pg_catalog."default",
    country_id character varying(100) COLLATE pg_catalog."default",
    taluk_name_en character varying(200) COLLATE pg_catalog."default",
    taluk_name_ml character varying(200) COLLATE pg_catalog."default",
    village_name_en character varying(200) COLLATE pg_catalog."default",
    village_name_ml character varying(200) COLLATE pg_catalog."default",
    postoffice_name_en character varying(200) COLLATE pg_catalog."default",
    postoffice_name_ml character varying(200) COLLATE pg_catalog."default",
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    location_type character varying(150) COLLATE pg_catalog."default",
    housename_ml character varying(500) COLLATE pg_catalog."default",
    housename_en character varying(500) COLLATE pg_catalog."default",
    mig_ackno character varying(64) COLLATE pg_catalog."default",
    mig_ack_no character varying(64) COLLATE pg_catalog."default",
    lbtype character varying(200) COLLATE pg_catalog."default",
    postal_code character varying(200) COLLATE pg_catalog."default",
    province_name_en character varying(200) COLLATE pg_catalog."default",
    province_name_ml character varying(200) COLLATE pg_catalog."default",
    city_town_village character varying(200) COLLATE pg_catalog."default",
    addr_lb_name character varying(200) COLLATE pg_catalog."default",
    addr_sameas_present boolean
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_address_registry_log
    OWNER to postgres;
--13
-- Table: public.eg_death_cert_request

-- DROP TABLE IF EXISTS public.eg_death_cert_request;

CREATE TABLE IF NOT EXISTS public.eg_death_cert_request
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    ack_no character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdby character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint NOT NULL,
    deathdtlid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    filestoreid character varying(256) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    status character varying(64) COLLATE pg_catalog."default",
    additionaldetail jsonb,
    embeddedurl character varying(64) COLLATE pg_catalog."default",
    dateofissue bigint,
    counter integer,
    certificate_no character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_death_cert_request_registry_pkey PRIMARY KEY (id),
    CONSTRAINT eg_death_cert_request_registry_fkey FOREIGN KEY (deathdtlid)
        REFERENCES public.eg_death_dtls_registry (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_cert_request
    OWNER to postgres;
--14
-- Table: public.eg_death_cert_request_audit

-- DROP TABLE IF EXISTS public.eg_death_cert_request_audit;

CREATE TABLE IF NOT EXISTS public.eg_death_cert_request_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    ack_no character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdby character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint NOT NULL,
    deathdtlid character varying(64) COLLATE pg_catalog."default",
    filestoreid character varying(256) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    status character varying(64) COLLATE pg_catalog."default",
    additionaldetail jsonb,
    embeddedurl character varying(64) COLLATE pg_catalog."default",
    dateofissue bigint,
    counter integer,
    certificate_no character varying(64) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.eg_death_cert_request_audit
    OWNER to postgres;