ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS aadhar_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS name_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS deathdate_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS deathplace_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS gender_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS mother_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS father_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS spouse_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS presentaddr_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS permanentaddr_corrflag  boolean;
ALTER TABLE eg_death_dtls ADD COLUMN IF NOT EXISTS previous_ack_no  character varying(100);

ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS aadhar_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS name_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS deathdate_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS deathplace_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS gender_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS mother_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS father_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS spouse_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS presentaddr_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS permanentaddr_corrflag  boolean;
ALTER TABLE eg_death_dtls_log ADD COLUMN IF NOT EXISTS previous_ack_no  character varying(100);