export const BIRTH_INCLUSION_FIELD_NAMES = {
    CHILD_DOB: "CHILD_DOB",
    CHILD_NAME: "CHILD_NAME",
    CHILD_SEX: "CHILD_SEX",
    CHILD_AADHAAR: "CHILD_AADHAAR",
    FATHER_DETAILS: "FATHER_DETAILS",
    MOTHER_DETAILS: "MOTHER_DETAILS",
    SPOUSE_DETAILS: "SPOUSE_DETAILS",
    PRESENT_ADDRESS: "PRESENT_ADDRESS"
}

export const BIRTH_INCLUSION_DOC_FLAGS = {
    STUDENT : "STUDENT_CHANGE",
    NAME_CORRECTION: "NAME_CORRECTION_CHANGE",
    AGE_CORRECTION: "AGE_CORRECTION_CHANGE",
    INSTITUTIONAL_SEX_CHANGE : "INSTITUTIONAL_SEX_CHANGE",
    NON_INSTITUTIONAL_SEX_CHANGE_MINOR: "NON_INSTITUTIONAL_SEX_CHANGE_MINOR",
    NON_INSTITUTIONAL_SEX_CHANGE_MAJOR: "NON_INSTITUTIONAL_SEX_CHANGE_MAJOR",
    FATHER_DETAILS: "FATHER_DETAILS",
    MOTHER_DETAILS: "MOTHER_DETAILS",
    PRESENT_ADDRESS: "PRESENT_ADDRESS"
}

export const MARRIAGE_INCLUSION_FIELD_NAMES = {
    CHILD_DOB: "CHILD_DOB",
    GROOM_NAME_EN: "GROOM_NAME_EN",
    CHILD_SEX: "CHILD_SEX",
    CHILD_WARD: "CHILD_WARD",
    FATHER_DETAILS: "FATHER_DETAILS",
    MOTHER_DETAILS: "MOTHER_DETAILS",
    PRESENT_ADDRESS: "PRESENT_ADDRESS"
}



export const DEATH_CORRECTION_FIELD_NAMES = {
    CHILD_DOB: "CHILD_DOB",
    DECEASED_AADHAR: "DECEASED_AADHAR",
    DECEASED_NAME_EN: "DECEASED_NAME_EN",
    DECEASED_NAME_ML: "DECEASED_FIRST_NAME_ML",
    MOTHERS_NAME: "MOTHERS_NAME",
    FATHERS_NAME: "FATHERS_NAME",
    SPOUSE_NAME: "SPOUSE_NAME",
    ADDRESS_EN: "ADDRESS_EN",
    ADDRESS_ML: "ADDRESS_ML",
    PLACE_OF_DEATH: "PLACE_OF_DEATH",
    GENDER: "GENDER"
}

export const STATE_CODE= {
    KL:"kl"
}