export const BIRTH_INCLUSION_FIELD_NAMES = {
    CHILD_DOB: "CHILD_DOB",
    CHILD_NAME: "CHILD_NAME",
    CHILD_SEX: "CHILD_SEX",
    // FATHER_DETAILS: "FATHER_DETAILS",
    // MOTHER_DETAILS: "MOTHER_DETAILS",
    // PRESENT_ADDRESS: "PRESENT_ADDRESS"
}

export const MARRIAGE_INCLUSION_FIELD_NAMES = {
    CHILD_DOB: "CHILD_DOB",
    CHILD_NAME: "CHILD_NAME",
    CHILD_SEX: "CHILD_SEX",
    FATHER_DETAILS: "FATHER_DETAILS",
    MOTHER_DETAILS: "MOTHER_DETAILS",
    PRESENT_ADDRESS: "PRESENT_ADDRESS"
}



export const DEATH_CORRECTION_FIELD_NAMES = {
    CHILD_DOB: "CHILD_DOB",
    DECEASED_AADHAR: "DECEASED_AADHAR",
    DECEASED_FIRST_NAME: "DECEASED_FIRST_NAME",
    DECEASED_MIDDLE_NAME: "DECEASED_MIDDLE_NAME",
}

