CREATE TABLE IF NOT EXISTS public.eg_marriage_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    dateofmarriage bigint,
    dateofreporting bigint,
    districtid character varying(64) COLLATE pg_catalog."default",
    lbtype character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    placetype character varying(64) COLLATE pg_catalog."default",
    placeid character varying(1000) COLLATE pg_catalog."default",
    placename_en character varying(1000) COLLATE pg_catalog."default",
    placename_ml character varying(1000) COLLATE pg_catalog."default",
    houseno_and_name_en character varying(2500) COLLATE pg_catalog."default",
    houseno_and_name_ml character varying(2500) COLLATE pg_catalog."default",
    street_name_en character varying(1000) COLLATE pg_catalog."default",
    street_name_ml character varying(1000) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(64) COLLATE pg_catalog."default",
    marriage_type character varying(64) COLLATE pg_catalog."default",
    oth_marriage_type character varying(200) COLLATE pg_catalog."default",
    landmark character varying(1000) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    applicationtype character varying(64) COLLATE pg_catalog."default" NOT NULL,
    businessservice character varying(64) COLLATE pg_catalog."default" NOT NULL,
    workflowcode character varying(64) COLLATE pg_catalog."default" NOT NULL,
    applicationnumber character varying(64) COLLATE pg_catalog."default",
    registrationno character varying(64) COLLATE pg_catalog."default",
    registration_date bigint,
    action character varying(64) COLLATE pg_catalog."default",
    status character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    domcorreflag boolean,
    placeidcorrflag boolean,
    groomnamecorreflag boolean,
    bridenamecorreflag boolean,
    groomagecorreflag boolean,
    brideagecorreflag boolean,
    groomdobcorreflag boolean,
    bridedobcorreflag boolean,
    groompermanentaddrcorreflag boolean,
    bridepermanentaddrcorreflag boolean,
    groommothercorreflag boolean,
    bridemothercorreflag boolean,
    groomfathercorreflag boolean,
    bridefathercorreflag boolean,
    groomguardiancorreflag boolean,
    brideguardiancorreflag boolean,
    villageid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    brideurl character varying(2000) COLLATE pg_catalog."default",
    groomurl character varying(2000) COLLATE pg_catalog."default",
    imageuuid character varying(64) COLLATE pg_catalog."default",
    bride_filestoreid character varying(256) COLLATE pg_catalog."default",
    groom_filestoreid character varying(256) COLLATE pg_catalog."default",
    bride_expired boolean,
    groom_expired boolean,
    module_code character varying(64) COLLATE pg_catalog."default",
    is_backward boolean,
    amount bigint,
    zonal_office character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT eg_marriage_place_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_marriage_place_details_applicationnumber_fkey UNIQUE (applicationnumber),
    CONSTRAINT eg_marriage_place_details_registrationno_fkey UNIQUE (registrationno, applicationnumber)
);


CREATE TABLE IF NOT EXISTS public.eg_marriage_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    dateofmarriage bigint,
    dateofreporting bigint,
    districtid character varying(64) COLLATE pg_catalog."default",
    lbtype character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    placetype character varying(64) COLLATE pg_catalog."default",
    placeid character varying(1000) COLLATE pg_catalog."default",
    placename_en character varying(1000) COLLATE pg_catalog."default",
    placename_ml character varying(1000) COLLATE pg_catalog."default",
    houseno_and_name_en character varying(2500) COLLATE pg_catalog."default",
    houseno_and_name_ml character varying(2500) COLLATE pg_catalog."default",
    street_name_en character varying(1000) COLLATE pg_catalog."default",
    street_name_ml character varying(1000) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(64) COLLATE pg_catalog."default",
    marriage_type character varying(64) COLLATE pg_catalog."default",
    oth_marriage_type character varying(200) COLLATE pg_catalog."default",
    landmark character varying(1000) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    applicationtype character varying(64) COLLATE pg_catalog."default" NOT NULL,
    businessservice character varying(64) COLLATE pg_catalog."default" NOT NULL,
    workflowcode character varying(64) COLLATE pg_catalog."default" NOT NULL,
    applicationnumber character varying(64) COLLATE pg_catalog."default",
    registrationno character varying(64) COLLATE pg_catalog."default",
    registration_date bigint,
    action character varying(64) COLLATE pg_catalog."default",
    status character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    domcorreflag boolean,
    placeidcorrflag boolean,
    groomnamecorreflag boolean,
    bridenamecorreflag boolean,
    groomagecorreflag boolean,
    brideagecorreflag boolean,
    groomdobcorreflag boolean,
    bridedobcorreflag boolean,
    groompermanentaddrcorreflag boolean,
    bridepermanentaddrcorreflag boolean,
    groommothercorreflag boolean,
    bridemothercorreflag boolean,
    groomfathercorreflag boolean,
    bridefathercorreflag boolean,
    groomguardiancorreflag boolean,
    brideguardiancorreflag boolean,
    villageid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    brideurl character varying(2000) COLLATE pg_catalog."default",
    groomurl character varying(2000) COLLATE pg_catalog."default",
    imageuuid character varying(64) COLLATE pg_catalog."default",
    bride_filestoreid character varying(256) COLLATE pg_catalog."default",
    groom_filestoreid character varying(256) COLLATE pg_catalog."default",
    bride_expired boolean,
    groom_expired boolean,
    module_code character varying(64) COLLATE pg_catalog."default",
    is_backward boolean,
    amount bigint,
    zonal_office character varying(100) COLLATE pg_catalog."default"
);


CREATE TABLE IF NOT EXISTS public.eg_marriage_permanent_address_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    housename_no_en character varying(2500) COLLATE pg_catalog."default",
    housename_no_ml character varying(2500) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(1000) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(2000) COLLATE pg_catalog."default",
    street_name_ml character varying(2000) COLLATE pg_catalog."default",
    districtid character varying(64) COLLATE pg_catalog."default",
    stateid character varying(64) COLLATE pg_catalog."default",
    poid character varying(64) COLLATE pg_catalog."default",
    pinno character varying(10) COLLATE pg_catalog."default",
    countryid character varying(64) COLLATE pg_catalog."default",
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    tenantid character varying(64) COLLATE pg_catalog."default",
    poname_en character varying(64) COLLATE pg_catalog."default",
    ot_address1_en character varying(2500) COLLATE pg_catalog."default",
    ot_address1_ml character varying(2500) COLLATE pg_catalog."default",
    ot_address2_en character varying(2500) COLLATE pg_catalog."default",
    ot_address2_ml character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_en character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_ml character varying(2500) COLLATE pg_catalog."default",
    ot_zipcode character varying(10) COLLATE pg_catalog."default",
    poname_ml character varying(64) COLLATE pg_catalog."default",
    city_town_village character varying(1000) COLLATE pg_catalog."default",
    state_name character varying(1000) COLLATE pg_catalog."default",
    district_name character varying(1000) COLLATE pg_catalog."default",
    country_name character varying(1000) COLLATE pg_catalog."default",
    permanent_tenentid character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_marriage_permanent_address_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_marriage_permanent_address_details_fkey FOREIGN KEY (marriageid)
        REFERENCES public.eg_marriage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS public.eg_marriage_permanent_address_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    housename_no_en character varying(2500) COLLATE pg_catalog."default",
    housename_no_ml character varying(2500) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(1000) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(2000) COLLATE pg_catalog."default",
    street_name_ml character varying(2000) COLLATE pg_catalog."default",
    districtid character varying(64) COLLATE pg_catalog."default",
    stateid character varying(64) COLLATE pg_catalog."default",
    poid character varying(64) COLLATE pg_catalog."default",
    pinno character varying(10) COLLATE pg_catalog."default",
    countryid character varying(64) COLLATE pg_catalog."default",
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    tenantid character varying(64) COLLATE pg_catalog."default",
    poname_en character varying(64) COLLATE pg_catalog."default",
    ot_address1_en character varying(2500) COLLATE pg_catalog."default",
    ot_address1_ml character varying(2500) COLLATE pg_catalog."default",
    ot_address2_en character varying(2500) COLLATE pg_catalog."default",
    ot_address2_ml character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_en character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_ml character varying(2500) COLLATE pg_catalog."default",
    ot_zipcode character varying(10) COLLATE pg_catalog."default",
    poname_ml character varying(64) COLLATE pg_catalog."default",
    city_town_village character varying(1000) COLLATE pg_catalog."default",
    state_name character varying(1000) COLLATE pg_catalog."default",
    district_name character varying(1000) COLLATE pg_catalog."default",
    country_name character varying(1000) COLLATE pg_catalog."default",
    permanent_tenentid character varying(64) COLLATE pg_catalog."default"
);
CREATE TABLE IF NOT EXISTS public.eg_marriage_present_address_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    housename_no_en character varying(2500) COLLATE pg_catalog."default",
    housename_no_ml character varying(2500) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(1000) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(2000) COLLATE pg_catalog."default",
    street_name_ml character varying(2000) COLLATE pg_catalog."default",
    districtid character varying(64) COLLATE pg_catalog."default",
    stateid character varying(64) COLLATE pg_catalog."default",
    poid character varying(64) COLLATE pg_catalog."default",
    pinno character varying(10) COLLATE pg_catalog."default",
    countryid character varying(64) COLLATE pg_catalog."default",
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    same_as_permanent boolean,
    tenantid character varying(64) COLLATE pg_catalog."default",
    poname_en character varying(64) COLLATE pg_catalog."default",
    ot_address1_en character varying(2500) COLLATE pg_catalog."default",
    ot_address1_ml character varying(2500) COLLATE pg_catalog."default",
    ot_address2_en character varying(2500) COLLATE pg_catalog."default",
    ot_address2_ml character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_en character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_ml character varying(2500) COLLATE pg_catalog."default",
    ot_zipcode character varying(10) COLLATE pg_catalog."default",
    poname_ml character varying(64) COLLATE pg_catalog."default",
    city_town_village character varying(1000) COLLATE pg_catalog."default",
    present_tenentid character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_marriage_present_address_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_marriage_present_address_details_fkey FOREIGN KEY (marriageid)
        REFERENCES public.eg_marriage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.eg_marriage_present_address_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    housename_no_en character varying(2500) COLLATE pg_catalog."default",
    housename_no_ml character varying(2500) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(1000) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(2000) COLLATE pg_catalog."default",
    street_name_ml character varying(2000) COLLATE pg_catalog."default",
    districtid character varying(64) COLLATE pg_catalog."default",
    stateid character varying(64) COLLATE pg_catalog."default",
    poid character varying(64) COLLATE pg_catalog."default",
    pinno character varying(10) COLLATE pg_catalog."default",
    countryid character varying(64) COLLATE pg_catalog."default",
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    same_as_permanent boolean,
    tenantid character varying(64) COLLATE pg_catalog."default",
    poname_en character varying(64) COLLATE pg_catalog."default",
    ot_address1_en character varying(2500) COLLATE pg_catalog."default",
    ot_address1_ml character varying(2500) COLLATE pg_catalog."default",
    ot_address2_en character varying(2500) COLLATE pg_catalog."default",
    ot_address2_ml character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_en character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_ml character varying(2500) COLLATE pg_catalog."default",
    ot_zipcode character varying(10) COLLATE pg_catalog."default",
    poname_ml character varying(64) COLLATE pg_catalog."default",
    city_town_village character varying(1000) COLLATE pg_catalog."default",
    present_tenentid character varying(64) COLLATE pg_catalog."default"
);
CREATE TABLE IF NOT EXISTS public.eg_marriage_witness_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    aadharno character varying(200) COLLATE pg_catalog."default",
    name_en character varying(200) COLLATE pg_catalog."default",
    name_ml character varying(200) COLLATE pg_catalog."default",
    age integer,
    address_en character varying(200) COLLATE pg_catalog."default",
    address_ml character varying(200) COLLATE pg_catalog."default",
    mobile bigint,
    is_esigned boolean,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    serial_no integer,
    tenantid character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_marriage_witness_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_marriage_witness_details_fkey FOREIGN KEY (marriageid)
        REFERENCES public.eg_marriage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.eg_marriage_witness_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    aadharno character varying(200) COLLATE pg_catalog."default",
    name_en character varying(200) COLLATE pg_catalog."default",
    name_ml character varying(200) COLLATE pg_catalog."default",
    age integer,
    address_en character varying(200) COLLATE pg_catalog."default",
    address_ml character varying(200) COLLATE pg_catalog."default",
    mobile bigint,
    is_esigned boolean,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    serial_no integer,
    tenantid character varying(64) COLLATE pg_catalog."default"
);
CREATE TABLE IF NOT EXISTS public.eg_marriage_bride_groom_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    residentship character varying(64) COLLATE pg_catalog."default",
    aadharno character varying(200) COLLATE pg_catalog."default",
    passportno character varying(1000) COLLATE pg_catalog."default",
    socialsecurityno character varying(64) COLLATE pg_catalog."default",
    firstname_en character varying(200) COLLATE pg_catalog."default",
    firstname_ml character varying(200) COLLATE pg_catalog."default",
    middlename_en character varying(200) COLLATE pg_catalog."default",
    middlename_ml character varying(200) COLLATE pg_catalog."default",
    lastname_en character varying(200) COLLATE pg_catalog."default",
    lastname_ml character varying(200) COLLATE pg_catalog."default",
    mobile bigint,
    emailid character varying(300) COLLATE pg_catalog."default",
    gender character varying(20) COLLATE pg_catalog."default",
    dateofbirth bigint,
    age integer,
    parent_guardian character varying(64) COLLATE pg_catalog."default",
    fathername_en character varying(200) COLLATE pg_catalog."default",
    fathername_ml character varying(200) COLLATE pg_catalog."default",
    mothername_en character varying(200) COLLATE pg_catalog."default",
    mothername_ml character varying(200) COLLATE pg_catalog."default",
    father_aadharno character varying(200) COLLATE pg_catalog."default",
    mother_aadharno character varying(200) COLLATE pg_catalog."default",
    guardianname_en character varying(200) COLLATE pg_catalog."default",
    guardianname_ml character varying(200) COLLATE pg_catalog."default",
    guardian_aadharno character varying(200) COLLATE pg_catalog."default",
    maritalstatusid character varying(64) COLLATE pg_catalog."default",
    is_spouse_living boolean,
    no_of_spouse_living integer,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_marriage_bride_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_marriage_bride_details_fkey FOREIGN KEY (marriageid)
        REFERENCES public.eg_marriage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.eg_marriage_bride_groom_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    residentship character varying(64) COLLATE pg_catalog."default",
    aadharno character varying(200) COLLATE pg_catalog."default",
    passportno character varying(1000) COLLATE pg_catalog."default",
    socialsecurityno character varying(64) COLLATE pg_catalog."default",
    firstname_en character varying(200) COLLATE pg_catalog."default",
    firstname_ml character varying(200) COLLATE pg_catalog."default",
    middlename_en character varying(200) COLLATE pg_catalog."default",
    middlename_ml character varying(200) COLLATE pg_catalog."default",
    lastname_en character varying(200) COLLATE pg_catalog."default",
    lastname_ml character varying(200) COLLATE pg_catalog."default",
    mobile bigint,
    emailid character varying(300) COLLATE pg_catalog."default",
    gender character varying(20) COLLATE pg_catalog."default",
    dateofbirth bigint,
    age integer,
    parent_guardian character varying(64) COLLATE pg_catalog."default",
    fathername_en character varying(200) COLLATE pg_catalog."default",
    fathername_ml character varying(200) COLLATE pg_catalog."default",
    mothername_en character varying(200) COLLATE pg_catalog."default",
    mothername_ml character varying(200) COLLATE pg_catalog."default",
    father_aadharno character varying(200) COLLATE pg_catalog."default",
    mother_aadharno character varying(200) COLLATE pg_catalog."default",
    guardianname_en character varying(200) COLLATE pg_catalog."default",
    guardianname_ml character varying(200) COLLATE pg_catalog."default",
    guardian_aadharno character varying(200) COLLATE pg_catalog."default",
    maritalstatusid character varying(64) COLLATE pg_catalog."default",
    is_spouse_living boolean,
    no_of_spouse_living integer,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.eg_marriage_document
(
    id character varying(128) COLLATE pg_catalog."default",
    tenantid character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_description character varying(140) COLLATE pg_catalog."default",
    filestoreid character varying(1024) COLLATE pg_catalog."default",
    document_link character varying(1024) COLLATE pg_catalog."default",
    file_type character varying(20) COLLATE pg_catalog."default",
    file_size bigint,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL,
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    applicationnumber character varying(64) COLLATE pg_catalog."default",
    updated_flag integer,
    registrationno character varying(64) COLLATE pg_catalog."default",
    correction_id character varying(64) COLLATE pg_catalog."default",
    correction_field_name character varying(1024) COLLATE pg_catalog."default",
    applicationtype character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_marriage_document_pkey UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS public.eg_marriage_document_audit
(
    operation character(1) COLLATE pg_catalog."default" NOT NULL,
    stamp timestamp without time zone NOT NULL,
    id character varying(128) COLLATE pg_catalog."default",
    tenantid character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_description character varying(140) COLLATE pg_catalog."default",
    filestoreid character varying(1024) COLLATE pg_catalog."default",
    document_link character varying(1024) COLLATE pg_catalog."default",
    file_type character varying(20) COLLATE pg_catalog."default",
    file_size bigint,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL,
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    applicationnumber character varying(64) COLLATE pg_catalog."default",
    updated_flag integer,
    registrationno character varying(64) COLLATE pg_catalog."default",
    correction_id character varying(64) COLLATE pg_catalog."default",
    correction_field_name character varying(1024) COLLATE pg_catalog."default",
    applicationtype character varying(64) COLLATE pg_catalog."default"
);
CREATE TABLE IF NOT EXISTS public.eg_register_marriage_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    dateofmarriage bigint,
    dateofreporting bigint,
    districtid character varying(64) COLLATE pg_catalog."default",
    lbtype character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    placetype character varying(64) COLLATE pg_catalog."default",
    placeid character varying(64) COLLATE pg_catalog."default",
    placename_en character varying(1000) COLLATE pg_catalog."default",
    placename_ml character varying(1000) COLLATE pg_catalog."default",
    housenameno_en character varying(1000) COLLATE pg_catalog."default",
    housenameno_ml character varying(1000) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(1000) COLLATE pg_catalog."default",
    street_name_ml character varying(1000) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(64) COLLATE pg_catalog."default",
    marriage_type character varying(64) COLLATE pg_catalog."default",
    oth_marriage_type character varying(200) COLLATE pg_catalog."default",
    landmark character varying(1000) COLLATE pg_catalog."default",
    registrationno character varying(64) COLLATE pg_catalog."default",
    registration_date bigint,
    registration_status character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    applicationnumber character varying(64) COLLATE pg_catalog."default",
    is_migrated boolean,
    migrated_date bigint,
    migrated_marriage_type character varying(64) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    brideurl character varying(2000) COLLATE pg_catalog."default",
    groomurl character varying(2000) COLLATE pg_catalog."default",
    imageuuid character varying(64) COLLATE pg_catalog."default",
    bride_filestoreid character varying(256) COLLATE pg_catalog."default",
    groom_filestoreid character varying(256) COLLATE pg_catalog."default",
    bride_expired boolean,
    groom_expired boolean,
    module_code character varying(64) COLLATE pg_catalog."default",
    is_backward boolean,
    certificateno character varying(64) COLLATE pg_catalog."default",
    certificatenumber character varying(64) COLLATE pg_catalog."default",
    zonal_office character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT eg_register_marriage_place_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_register_marriage_place_details_applicationnumber_fkey UNIQUE (applicationnumber, tenantid)
);

CREATE TABLE IF NOT EXISTS public.eg_register_marriage_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    dateofmarriage bigint,
    dateofreporting bigint,
    districtid character varying(64) COLLATE pg_catalog."default",
    lbtype character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    placetype character varying(64) COLLATE pg_catalog."default",
    placeid character varying(64) COLLATE pg_catalog."default",
    placename_en character varying(1000) COLLATE pg_catalog."default",
    placename_ml character varying(1000) COLLATE pg_catalog."default",
    housenameno_en character varying(1000) COLLATE pg_catalog."default",
    housenameno_ml character varying(1000) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(1000) COLLATE pg_catalog."default",
    street_name_ml character varying(1000) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(64) COLLATE pg_catalog."default",
    marriage_type character varying(64) COLLATE pg_catalog."default",
    oth_marriage_type character varying(200) COLLATE pg_catalog."default",
    landmark character varying(1000) COLLATE pg_catalog."default",
    registrationno character varying(64) COLLATE pg_catalog."default",
    registration_date bigint,
    registration_status character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    applicationnumber character varying(64) COLLATE pg_catalog."default",
    is_migrated boolean,
    migrated_date bigint,
    migrated_marriage_type character varying(64) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    brideurl character varying(2000) COLLATE pg_catalog."default",
    groomurl character varying(2000) COLLATE pg_catalog."default",
    imageuuid character varying(64) COLLATE pg_catalog."default",
    bride_filestoreid character varying(256) COLLATE pg_catalog."default",
    groom_filestoreid character varying(256) COLLATE pg_catalog."default",
    bride_expired boolean,
    groom_expired boolean,
    module_code character varying(64) COLLATE pg_catalog."default",
    is_backward boolean,
    certificatenumber character varying(64) COLLATE pg_catalog."default",
    certificateno character varying(64) COLLATE pg_catalog."default",
    zonal_office character varying(100) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.eg_register_marriage_document
(
    id character varying(128) COLLATE pg_catalog."default",
    tenantid character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_description character varying(140) COLLATE pg_catalog."default",
    filestoreid character varying(1024) COLLATE pg_catalog."default",
    document_link character varying(1024) COLLATE pg_catalog."default",
    file_type character varying(20) COLLATE pg_catalog."default",
    file_size bigint,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL,
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    applicationnumber character varying(64) COLLATE pg_catalog."default",
    updated_flag integer,
    registrationno character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_register_marriage_document_fkey PRIMARY KEY (tenantid, document_type, document_name, marriageid, bride_groom, active),
    CONSTRAINT eg_register_marriage_document_pkey UNIQUE (id)
);
CREATE TABLE IF NOT EXISTS public.eg_register_marriage_document_audit
(
    id character varying(128) COLLATE pg_catalog."default",
    tenantid character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    document_description character varying(140) COLLATE pg_catalog."default",
    filestoreid character varying(1024) COLLATE pg_catalog."default",
    document_link character varying(1024) COLLATE pg_catalog."default",
    file_type character varying(20) COLLATE pg_catalog."default",
    file_size bigint,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL,
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    applicationnumber character varying(64) COLLATE pg_catalog."default",
    updated_flag integer,
    registrationno character varying(64) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.eg_register_marriage_permanent_address_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    housename_en character varying(2500) COLLATE pg_catalog."default",
    housename_ml character varying(2500) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(1000) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(2000) COLLATE pg_catalog."default",
    street_name_ml character varying(2000) COLLATE pg_catalog."default",
    districtid character varying(64) COLLATE pg_catalog."default",
    stateid character varying(64) COLLATE pg_catalog."default",
    poid character varying(64) COLLATE pg_catalog."default",
    poname_en character varying(64) COLLATE pg_catalog."default",
    poname_ml character varying(64) COLLATE pg_catalog."default",
    pinno character varying(10) COLLATE pg_catalog."default",
    countryid character varying(64) COLLATE pg_catalog."default",
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mig_chvackno character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    ot_address1_en character varying(2500) COLLATE pg_catalog."default",
    ot_address1_ml character varying(2500) COLLATE pg_catalog."default",
    ot_address2_en character varying(2500) COLLATE pg_catalog."default",
    ot_address2_ml character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_en character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_ml character varying(2500) COLLATE pg_catalog."default",
    ot_zipcode character varying(10) COLLATE pg_catalog."default",
    city_town_village character varying(1000) COLLATE pg_catalog."default",
    state_name character varying(1000) COLLATE pg_catalog."default",
    district_name character varying(1000) COLLATE pg_catalog."default",
    country_name character varying(1000) COLLATE pg_catalog."default",
    permanent_tenentid character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_register_marriage_permanent_address_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_register_marriage_permanent_address_details_fkey FOREIGN KEY (marriageid)
        REFERENCES public.eg_register_marriage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.eg_register_marriage_permanent_address_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    housename_en character varying(2500) COLLATE pg_catalog."default",
    housename_ml character varying(2500) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(1000) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(2000) COLLATE pg_catalog."default",
    street_name_ml character varying(2000) COLLATE pg_catalog."default",
    districtid character varying(64) COLLATE pg_catalog."default",
    stateid character varying(64) COLLATE pg_catalog."default",
    poid character varying(64) COLLATE pg_catalog."default",
    poname_en character varying(64) COLLATE pg_catalog."default",
    poname_ml character varying(64) COLLATE pg_catalog."default",
    pinno character varying(10) COLLATE pg_catalog."default",
    countryid character varying(64) COLLATE pg_catalog."default",
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mig_chvackno character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    ot_address1_en character varying(2500) COLLATE pg_catalog."default",
    ot_address1_ml character varying(2500) COLLATE pg_catalog."default",
    ot_address2_en character varying(2500) COLLATE pg_catalog."default",
    ot_address2_ml character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_en character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_ml character varying(2500) COLLATE pg_catalog."default",
    ot_zipcode character varying(10) COLLATE pg_catalog."default",
    city_town_village character varying(1000) COLLATE pg_catalog."default",
    state_name character varying(1000) COLLATE pg_catalog."default",
    district_name character varying(1000) COLLATE pg_catalog."default",
    country_name character varying(1000) COLLATE pg_catalog."default",
    permanent_tenentid character varying(64) COLLATE pg_catalog."default"
);
CREATE TABLE IF NOT EXISTS public.eg_register_marriage_present_address_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    housename_en character varying(2500) COLLATE pg_catalog."default",
    housename_ml character varying(2500) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(1000) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(2000) COLLATE pg_catalog."default",
    street_name_ml character varying(2000) COLLATE pg_catalog."default",
    districtid character varying(64) COLLATE pg_catalog."default",
    stateid character varying(64) COLLATE pg_catalog."default",
    poid character varying(64) COLLATE pg_catalog."default",
    poname_en character varying(64) COLLATE pg_catalog."default",
    poname_ml character varying(64) COLLATE pg_catalog."default",
    pinno character varying(10) COLLATE pg_catalog."default",
    countryid character varying(64) COLLATE pg_catalog."default",
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mig_chvackno character varying(64) COLLATE pg_catalog."default",
    same_as_permanent boolean,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    ot_address1_en character varying(2500) COLLATE pg_catalog."default",
    ot_address1_ml character varying(2500) COLLATE pg_catalog."default",
    ot_address2_en character varying(2500) COLLATE pg_catalog."default",
    ot_address2_ml character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_en character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_ml character varying(2500) COLLATE pg_catalog."default",
    ot_zipcode character varying(10) COLLATE pg_catalog."default",
    city_town_village character varying(1000) COLLATE pg_catalog."default",
    present_tenentid character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_register_marriage_present_address_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_register_marriage_present_address_details_fkey FOREIGN KEY (marriageid)
        REFERENCES public.eg_register_marriage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.eg_register_marriage_present_address_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    housename_en character varying(2500) COLLATE pg_catalog."default",
    housename_ml character varying(2500) COLLATE pg_catalog."default",
    villageid character varying(64) COLLATE pg_catalog."default",
    village_name character varying(1000) COLLATE pg_catalog."default",
    talukid character varying(64) COLLATE pg_catalog."default",
    taluk_name character varying(1000) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    ward_code character varying(64) COLLATE pg_catalog."default",
    locality_en character varying(1000) COLLATE pg_catalog."default",
    locality_ml character varying(1000) COLLATE pg_catalog."default",
    street_name_en character varying(2000) COLLATE pg_catalog."default",
    street_name_ml character varying(2000) COLLATE pg_catalog."default",
    districtid character varying(64) COLLATE pg_catalog."default",
    stateid character varying(64) COLLATE pg_catalog."default",
    poid character varying(64) COLLATE pg_catalog."default",
    poname_en character varying(64) COLLATE pg_catalog."default",
    poname_ml character varying(64) COLLATE pg_catalog."default",
    pinno character varying(10) COLLATE pg_catalog."default",
    countryid character varying(64) COLLATE pg_catalog."default",
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mig_chvackno character varying(64) COLLATE pg_catalog."default",
    same_as_permanent boolean,
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    ot_address1_en character varying(2500) COLLATE pg_catalog."default",
    ot_address1_ml character varying(2500) COLLATE pg_catalog."default",
    ot_address2_en character varying(2500) COLLATE pg_catalog."default",
    ot_address2_ml character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_en character varying(2500) COLLATE pg_catalog."default",
    ot_state_region_province_ml character varying(2500) COLLATE pg_catalog."default",
    ot_zipcode character varying(10) COLLATE pg_catalog."default",
    city_town_village character varying(1000) COLLATE pg_catalog."default",
    present_tenentid character varying(64) COLLATE pg_catalog."default"
);
CREATE TABLE IF NOT EXISTS public.eg_register_marriage_witness_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    aadharno character varying(200) COLLATE pg_catalog."default",
    name_en character varying(200) COLLATE pg_catalog."default",
    name_ml character varying(200) COLLATE pg_catalog."default",
    age integer,
    address_en character varying(200) COLLATE pg_catalog."default",
    address_ml character varying(200) COLLATE pg_catalog."default",
    mobile bigint,
    is_esigned boolean,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mig_chvackno character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    serial_no integer,
    tenantid character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_register_marriage_witness_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_register_marriage_witness_details_fkey FOREIGN KEY (marriageid)
        REFERENCES public.eg_register_marriage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.eg_register_marriage_witness_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    aadharno character varying(200) COLLATE pg_catalog."default",
    name_en character varying(200) COLLATE pg_catalog."default",
    name_ml character varying(200) COLLATE pg_catalog."default",
    age integer,
    address_en character varying(200) COLLATE pg_catalog."default",
    address_ml character varying(200) COLLATE pg_catalog."default",
    mobile bigint,
    is_esigned boolean,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mig_chvackno character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    serial_no integer,
    tenantid character varying(64) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.eg_register_marriage_bride_groom_details
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    residentship character varying(64) COLLATE pg_catalog."default",
    aadharno character varying(200) COLLATE pg_catalog."default",
    passportno character varying(1000) COLLATE pg_catalog."default",
    socialsecurityno character varying(64) COLLATE pg_catalog."default",
    firstname_en character varying(200) COLLATE pg_catalog."default",
    middlename_en character varying(200) COLLATE pg_catalog."default",
    lastname_en character varying(200) COLLATE pg_catalog."default",
    firstname_ml character varying(200) COLLATE pg_catalog."default",
    middlename_ml character varying(200) COLLATE pg_catalog."default",
    lastname_ml character varying(200) COLLATE pg_catalog."default",
    mobile bigint,
    emailid character varying(300) COLLATE pg_catalog."default",
    gender character varying(20) COLLATE pg_catalog."default",
    dateofbirth bigint,
    age integer,
    parent_guardian character varying(64) COLLATE pg_catalog."default",
    fathername_en character varying(200) COLLATE pg_catalog."default",
    mothername_en character varying(200) COLLATE pg_catalog."default",
    fathername_ml character varying(200) COLLATE pg_catalog."default",
    mothername_ml character varying(200) COLLATE pg_catalog."default",
    father_aadharno character varying(200) COLLATE pg_catalog."default",
    mother_aadharno character varying(200) COLLATE pg_catalog."default",
    guardianname_en character varying(200) COLLATE pg_catalog."default",
    guardianname_ml character varying(200) COLLATE pg_catalog."default",
    guardian_aadharno character varying(200) COLLATE pg_catalog."default",
    maritalstatusid character varying(64) COLLATE pg_catalog."default",
    is_spouse_living boolean,
    no_of_spouse_living integer,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mig_chvackno character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT eg_register_marriage_bride_details_pkey PRIMARY KEY (id),
    CONSTRAINT eg_register_marriage_bride_details_fkey FOREIGN KEY (marriageid)
        REFERENCES public.eg_register_marriage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.eg_register_marriage_bride_groom_details_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    residentship character varying(64) COLLATE pg_catalog."default",
    aadharno character varying(200) COLLATE pg_catalog."default",
    passportno character varying(1000) COLLATE pg_catalog."default",
    socialsecurityno character varying(64) COLLATE pg_catalog."default",
    firstname_en character varying(200) COLLATE pg_catalog."default",
    middlename_en character varying(200) COLLATE pg_catalog."default",
    lastname_en character varying(200) COLLATE pg_catalog."default",
    firstname_ml character varying(200) COLLATE pg_catalog."default",
    middlename_ml character varying(200) COLLATE pg_catalog."default",
    lastname_ml character varying(200) COLLATE pg_catalog."default",
    mobile bigint,
    emailid character varying(300) COLLATE pg_catalog."default",
    gender character varying(20) COLLATE pg_catalog."default",
    dateofbirth bigint,
    age integer,
    parent_guardian character varying(64) COLLATE pg_catalog."default",
    fathername_en character varying(200) COLLATE pg_catalog."default",
    mothername_en character varying(200) COLLATE pg_catalog."default",
    fathername_ml character varying(200) COLLATE pg_catalog."default",
    mothername_ml character varying(200) COLLATE pg_catalog."default",
    father_aadharno character varying(200) COLLATE pg_catalog."default",
    mother_aadharno character varying(200) COLLATE pg_catalog."default",
    guardianname_en character varying(200) COLLATE pg_catalog."default",
    guardianname_ml character varying(200) COLLATE pg_catalog."default",
    guardian_aadharno character varying(200) COLLATE pg_catalog."default",
    maritalstatusid character varying(64) COLLATE pg_catalog."default",
    is_spouse_living boolean,
    no_of_spouse_living integer,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    bride_groom character varying(64) COLLATE pg_catalog."default" NOT NULL,
    mig_chvackno character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    tenantid character varying(64) COLLATE pg_catalog."default"
);
CREATE TABLE IF NOT EXISTS public.eg_marriage_certificate
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    registrationno character varying(64) COLLATE pg_catalog."default",
    registrydetailsid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    filestoreid character varying(256) COLLATE pg_catalog."default",
    status character varying(25) COLLATE pg_catalog."default",
    additionaldetail jsonb,
    embeddedurl character varying(64) COLLATE pg_catalog."default",
    dateofissue bigint,
    tenantid character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    count integer,
    CONSTRAINT eg_marriage_certificate_request_pkey PRIMARY KEY (id),
    CONSTRAINT eg_marriage_certificate_request_fkey FOREIGN KEY (registrydetailsid)
        REFERENCES public.eg_register_marriage_details (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.eg_marriage_certificate_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    registrationno character varying(64) COLLATE pg_catalog."default",
    registrydetailsid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    filestoreid character varying(256) COLLATE pg_catalog."default",
    status character varying(25) COLLATE pg_catalog."default",
    additionaldetail jsonb,
    embeddedurl character varying(64) COLLATE pg_catalog."default",
    dateofissue bigint,
    tenantid character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedtime bigint,
    createdby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    count integer
);
CREATE TABLE IF NOT EXISTS public.eg_marriage_correction
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    correction_field_name character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    condition_code character varying(1024) COLLATE pg_catalog."default",
    specific_condition character varying(1024) COLLATE pg_catalog."default",
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    CONSTRAINT eg_marriage_correction_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.eg_marriage_correction_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    correction_field_name character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    condition_code character varying(1024) COLLATE pg_catalog."default",
    specific_condition character varying(1024) COLLATE pg_catalog."default",
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    CONSTRAINT eg_marriage_correction_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.eg_marriage_correction_child
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    correctionid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    correction_field_name character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    table_name character varying(1024) COLLATE pg_catalog."default",
    column_name character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    old_value character varying(2500) COLLATE pg_catalog."default" NOT NULL,
    new_value character varying(2500) COLLATE pg_catalog."default" NOT NULL,
    column_ character varying(1024) COLLATE pg_catalog."default",
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    CONSTRAINT eg_marriage_correction_child_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.eg_marriage_correction_child_audit
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    marriageid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    correctionid character varying(64) COLLATE pg_catalog."default" NOT NULL,
    correction_field_name character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    table_name character varying(1024) COLLATE pg_catalog."default",
    column_name character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    old_value character varying(2500) COLLATE pg_catalog."default" NOT NULL,
    new_value character varying(2500) COLLATE pg_catalog."default" NOT NULL,
    column_ character varying(1024) COLLATE pg_catalog."default",
    createdby character varying(64) COLLATE pg_catalog."default",
    createdtime bigint,
    lastmodifiedby character varying(64) COLLATE pg_catalog."default",
    lastmodifiedtime bigint,
    CONSTRAINT eg_marriage_correction_child_audit_pkey PRIMARY KEY (id)
);